Nurfed_UnitLayouts = {
	["Layout1"] = {
		["Name"] = { point = "TOPLEFT", relativepoint = "TOPLEFT", x = 6, y = -3, width = 110, height = 14, textheight = 10, shown = true },
		["HealthPerc"] = { point = "TOPRIGHT", relativepoint = "TOPRIGHT", x = -6, y = -3, width = 33, height = 14, textheight = 10, shown = true },
		["HealthText"] = false,
		["ManaText"] = false,
		["StatusIcon"] = { point = "RIGHT", relativeto = "HealthPerc", relativepoint = "LEFT", x = 0, y = 0, width = 15, height = 15 },
		["RankIcon"] = { point = "RIGHT", relativeto = "HealthPerc", relativepoint = "LEFT", x = 0, y = 0, width = 13, height = 13 },
		["HappinessIcon"] = { point = "BOTTOMRIGHT", relativepoint = "TOPRIGHT", x = -3, y = 0, width = 13, height = 13 },
		["PVPIcon"] = { point = "TOPLEFT", relativepoint = "TOPLEFT", x = -5, y = -1, width = 21, height = 21 },
		["LeaderIcon"] = { point = "TOPLEFT", relativeto = "PVPIcon", relativepoint = "BOTTOMLEFT", x = 0, y = 7, width = 14, height = 14 },
		["MasterIcon"] = { point = "TOP", relativeto = "LeaderIcon", relativepoint = "BOTTOM", x = 0, y = 0, width = 14, height = 14 },
		["Highlight"] = { point = "TOP", relativepoint = "TOP", x = 0, y = -5, width = 143, height = 12 },
		["Class"] = { point = "TOPLEFT", relativeto = "Name", relativepoint = "BOTTOMLEFT", x = 0, y = 0, width = 20, height = 20, shown = true },
		["HealthBar"] = { point = "TOPLEFT", relativeto = "Class", relativepoint = "TOPRIGHT", x = 0, y = 0, width = 118, height = 10, shown = true },
		["ManaBar"] = { point = "TOPLEFT", relativeto = "HealthBar", relativepoint = "BOTTOMLEFT", x = 0, y = -2, width = 118, height = 8, shown = true },
		["XPBar"] = { point = "TOPLEFT", relativeto = "Class", relativepoint = "BOTTOMLEFT", x = 0, y = -2, width = 138, height = 8 },
		["BG"] = { point = "TOP", relativepoint = "TOP", x = 0, y = -3, width = 140, height = 15, shown = true },
		["Debuff1"] = { point = "TOPLEFT", relativepoint = "BOTTOMLEFT", x = 3, y = 0 },
		["Debuff2"] = { point = "LEFT", relativeto = "Debuff1", relativepoint = "RIGHT", x = 1, y = 0 },
		["Debuff3"] = { point = "LEFT", relativeto = "Debuff2", relativepoint = "RIGHT", x = 1, y = 0 },
		["Debuff4"] = { point = "LEFT", relativeto = "Debuff3", relativepoint = "RIGHT", x = 1, y = 0 },
		["Debuff5"] = { point = "LEFT", relativeto = "Debuff4", relativepoint = "RIGHT", x = 1, y = 0 },
		["Debuff6"] = { point = "LEFT", relativeto = "Debuff5", relativepoint = "RIGHT", x = 1, y = 0 },
		["Debuff7"] = { point = "LEFT", relativeto = "Debuff6", relativepoint = "RIGHT", x = 1, y = 0 },
		["Debuff8"] = { point = "LEFT", relativeto = "Debuff7", relativepoint = "RIGHT", x = 1, y = 0 },
		["Debuff9"] = { point = "TOPLEFT", relativeto = "Debuff1", relativepoint = "BOTTOMLEFT", x = 0, y = -2 },
		["Debuff10"] = { point = "LEFT", relativeto = "Debuff9", relativepoint = "RIGHT", x = 1, y = 0 },
		["Debuff11"] = { point = "LEFT", relativeto = "Debuff10", relativepoint = "RIGHT", x = 1, y = 0 },
		["Debuff12"] = { point = "LEFT", relativeto = "Debuff11", relativepoint = "RIGHT", x = 1, y = 0 },
		["Debuff13"] = { point = "LEFT", relativeto = "Debuff12", relativepoint = "RIGHT", x = 1, y = 0 },
		["Debuff14"] = { point = "LEFT", relativeto = "Debuff13", relativepoint = "RIGHT", x = 1, y = 0 },
		["Debuff15"] = { point = "LEFT", relativeto = "Debuff14", relativepoint = "RIGHT", x = 1, y = 0 },
		["Debuff16"] = { point = "LEFT", relativeto = "Debuff15", relativepoint = "RIGHT", x = 1, y = 0 },
		["Buff1"] = { point = "TOPLEFT", relativeto = "Debuff1", relativepoint = "BOTTOMLEFT", x = 0, y = -2 },
		["Buff2"] = { point = "LEFT", relativeto = "Buff1", relativepoint = "RIGHT", x = 1, y = 0 },
		["Buff3"] = { point = "LEFT", relativeto = "Buff2", relativepoint = "RIGHT", x = 1, y = 0 },
		["Buff4"] = { point = "LEFT", relativeto = "Buff3", relativepoint = "RIGHT", x = 1, y = 0 },
		["Buff5"] = { point = "LEFT", relativeto = "Buff4", relativepoint = "RIGHT", x = 1, y = 0 },
		["Buff6"] = { point = "LEFT", relativeto = "Buff5", relativepoint = "RIGHT", x = 1, y = 0 },
		["Buff7"] = { point = "LEFT", relativeto = "Buff6", relativepoint = "RIGHT", x = 1, y = 0 },
		["Buff8"] = { point = "LEFT", relativeto = "Buff7", relativepoint = "RIGHT", x = 1, y = 0 },
	},
	["Layout2"] = {
		["Name"] = { point = "TOPLEFT", relativepoint = "TOPLEFT", x = 6, y = -3, width = 110, height = 14, textheight = 10, shown = true },
		["HealthPerc"] = { point = "TOPRIGHT", relativepoint = "TOPRIGHT", x = -6, y = -3, width = 33, height = 14, textheight = 10, shown = true },
		["HealthText"] = { point = "TOPRIGHT", relativeto = "HealthPerc", relativepoint = "BOTTOMRIGHT", x = 0, y = 0, width = 35, height = 8, align = "RIGHT", shown = true },
		["ManaText"] = { point = "TOPRIGHT", relativeto = "HealthText", relativepoint = "BOTTOMRIGHT", x = 0, y = -2, width = 35, height = 8, align = "RIGHT", shown = true },
		["StatusIcon"] = { point = "BOTTOMLEFT", relativepoint = "TOPLEFT", x = 3, y = 0, width = 15, height = 15 },
		["RankIcon"] = { point = "TOPRIGHT", relativepoint = "TOPRIGHT", x = 0, y = 0, width = 1, height = 1 },
		["HappinessIcon"] = { point = "BOTTOMRIGHT", relativepoint = "TOPRIGHT", x = -3, y = 0, width = 13, height = 13 },
		["PVPIcon"] = { point = "RIGHT", relativeto = "HealthPerc", relativepoint = "LEFT", x = 0, y = -5, width = 20, height = 20 },
		["LeaderIcon"] = { point = "TOPRIGHT", relativeto = "PVPIcon", relativepoint = "TOPLEFT", x = 0, y = 5, width = 10, height = 10 },
		["MasterIcon"] = { point = "TOP", relativeto = "LeaderIcon", relativepoint = "BOTTOM", x = 0, y = 3, width = 10, height = 10 },
		["Highlight"] = { point = "TOP", relativepoint = "TOP", x = 0, y = -5, width = 143, height = 12 },
		["Class"] = false,
		["HealthBar"] = { point = "TOPLEFT", relativeto = "Name", relativepoint = "BOTTOMLEFT", x = 0, y = 0, width = 100, height = 8, shown = true },
		["ManaBar"] = { point = "TOPLEFT", relativeto = "HealthBar", relativepoint = "BOTTOMLEFT", x = 0, y = -2, width = 100, height = 8, shown = true },
		["XPBar"] = { point = "TOPLEFT", relativeto = "Class", relativepoint = "BOTTOMLEFT", x = 0, y = -2, width = 138, height = 8 },
		["BG"] = { point = "TOP", relativepoint = "TOP", x = 0, y = -3, width = 140, height = 15, shown = true },
		["Debuff1"] = { point = "TOPLEFT", relativepoint = "BOTTOMLEFT", x = 3, y = 0 },
		["Debuff2"] = { point = "LEFT", relativeto = "Debuff1", relativepoint = "RIGHT", x = 1, y = 0 },
		["Debuff3"] = { point = "LEFT", relativeto = "Debuff2", relativepoint = "RIGHT", x = 1, y = 0 },
		["Debuff4"] = { point = "LEFT", relativeto = "Debuff3", relativepoint = "RIGHT", x = 1, y = 0 },
		["Debuff5"] = { point = "LEFT", relativeto = "Debuff4", relativepoint = "RIGHT", x = 1, y = 0 },
		["Debuff6"] = { point = "LEFT", relativeto = "Debuff5", relativepoint = "RIGHT", x = 1, y = 0 },
		["Debuff7"] = { point = "LEFT", relativeto = "Debuff6", relativepoint = "RIGHT", x = 1, y = 0 },
		["Debuff8"] = { point = "LEFT", relativeto = "Debuff7", relativepoint = "RIGHT", x = 1, y = 0 },
		["Debuff9"] = { point = "TOPLEFT", relativeto = "Debuff1", relativepoint = "BOTTOMLEFT", x = 0, y = -2 },
		["Debuff10"] = { point = "LEFT", relativeto = "Debuff9", relativepoint = "RIGHT", x = 1, y = 0 },
		["Debuff11"] = { point = "LEFT", relativeto = "Debuff10", relativepoint = "RIGHT", x = 1, y = 0 },
		["Debuff12"] = { point = "LEFT", relativeto = "Debuff11", relativepoint = "RIGHT", x = 1, y = 0 },
		["Debuff13"] = { point = "LEFT", relativeto = "Debuff12", relativepoint = "RIGHT", x = 1, y = 0 },
		["Debuff14"] = { point = "LEFT", relativeto = "Debuff13", relativepoint = "RIGHT", x = 1, y = 0 },
		["Debuff15"] = { point = "LEFT", relativeto = "Debuff14", relativepoint = "RIGHT", x = 1, y = 0 },
		["Debuff16"] = { point = "LEFT", relativeto = "Debuff15", relativepoint = "RIGHT", x = 1, y = 0 },
		["Buff1"] = { point = "TOPLEFT", relativeto = "Debuff1", relativepoint = "BOTTOMLEFT", x = 0, y = -2 },
		["Buff2"] = { point = "LEFT", relativeto = "Buff1", relativepoint = "RIGHT", x = 1, y = 0 },
		["Buff3"] = { point = "LEFT", relativeto = "Buff2", relativepoint = "RIGHT", x = 1, y = 0 },
		["Buff4"] = { point = "LEFT", relativeto = "Buff3", relativepoint = "RIGHT", x = 1, y = 0 },
		["Buff5"] = { point = "LEFT", relativeto = "Buff4", relativepoint = "RIGHT", x = 1, y = 0 },
		["Buff6"] = { point = "LEFT", relativeto = "Buff5", relativepoint = "RIGHT", x = 1, y = 0 },
		["Buff7"] = { point = "LEFT", relativeto = "Buff6", relativepoint = "RIGHT", x = 1, y = 0 },
		["Buff8"] = { point = "LEFT", relativeto = "Buff7", relativepoint = "RIGHT", x = 1, y = 0 },
	},
	["Layout3"] = {
		["Name"] = { point = "TOPLEFT", relativepoint = "TOPLEFT", x = 6, y = -3, width = 110, height = 10, textheight = 8, shown = true },
		["HealthPerc"] = { point = "RIGHT", relativeto = "MasterIcon", relativepoint = "LEFT", x = 0, y = 0, width = 33, height = 10, textheight = 8, shown = true },
		["HealthText"] = { point = "TOPLEFT", relativeto = "ManaBar", relativepoint = "BOTTOMLEFT", x = 0, y = -2, width = 69, height = 8, align = "LEFT", shown = true },
		["ManaText"] = { point = "TOPRIGHT", relativeto = "ManaBar", relativepoint = "BOTTOMRIGHT", x = 0, y = -2, width = 69, height = 8, align = "RIGHT", shown = true },
		["StatusIcon"] = { point = "TOPRIGHT", relativepoint = "TOPRIGHT", x = -6, y = -3, width = 10, height = 10 },
		["RankIcon"] = { point = "TOPRIGHT", relativepoint = "TOPRIGHT", x = 0, y = 0, width = 1, height = 1 },
		["HappinessIcon"] = { point = "BOTTOMRIGHT", relativepoint = "TOPRIGHT", x = -3, y = 0, width = 13, height = 13 },
		["PVPIcon"] = { point = "BOTTOM", relativepoint = "BOTTOM", x = 0, y = -6, width = 21, height = 21 },
		["LeaderIcon"] = { point = "RIGHT", relativeto = "StatusIcon", relativepoint = "LEFT", x = 0, y = 0, width = 10, height = 10 },
		["MasterIcon"] = { point = "RIGHT", relativeto = "LeaderIcon", relativepoint = "LEFT", x = 0, y = 0, width = 10, height = 10 },
		["Highlight"] = { point = "TOP", relativepoint = "TOP", x = 0, y = -5, width = 143, height = 8 },
		["Class"] = false,
		["HealthBar"] = { point = "TOPLEFT", relativeto = "Name", relativepoint = "BOTTOMLEFT", x = 0, y = 0, width = 138, height = 6, shown = true },
		["ManaBar"] = { point = "TOPLEFT", relativeto = "HealthBar", relativepoint = "BOTTOMLEFT", x = 0, y = -2, width = 138, height = 6, shown = true },
		["XPBar"] = { point = "TOPLEFT", relativeto = "ManaBar", relativepoint = "BOTTOMLEFT", x = 0, y = -2, width = 138, height = 8 },
		["BG"] = { point = "TOP", relativepoint = "TOP", x = 0, y = -3, width = 140, height = 10, shown = true },
		["Debuff1"] = { point = "TOPLEFT", relativepoint = "BOTTOMLEFT", x = 3, y = 0 },
		["Debuff2"] = { point = "LEFT", relativeto = "Debuff1", relativepoint = "RIGHT", x = 1, y = 0 },
		["Debuff3"] = { point = "LEFT", relativeto = "Debuff2", relativepoint = "RIGHT", x = 1, y = 0 },
		["Debuff4"] = { point = "LEFT", relativeto = "Debuff3", relativepoint = "RIGHT", x = 1, y = 0 },
		["Debuff5"] = { point = "LEFT", relativeto = "Debuff4", relativepoint = "RIGHT", x = 1, y = 0 },
		["Debuff6"] = { point = "LEFT", relativeto = "Debuff5", relativepoint = "RIGHT", x = 1, y = 0 },
		["Debuff7"] = { point = "LEFT", relativeto = "Debuff6", relativepoint = "RIGHT", x = 1, y = 0 },
		["Debuff8"] = { point = "LEFT", relativeto = "Debuff7", relativepoint = "RIGHT", x = 1, y = 0 },
		["Debuff9"] = { point = "TOPLEFT", relativeto = "Debuff1", relativepoint = "BOTTOMLEFT", x = 0, y = -2 },
		["Debuff10"] = { point = "LEFT", relativeto = "Debuff9", relativepoint = "RIGHT", x = 1, y = 0 },
		["Debuff11"] = { point = "LEFT", relativeto = "Debuff10", relativepoint = "RIGHT", x = 1, y = 0 },
		["Debuff12"] = { point = "LEFT", relativeto = "Debuff11", relativepoint = "RIGHT", x = 1, y = 0 },
		["Debuff13"] = { point = "LEFT", relativeto = "Debuff12", relativepoint = "RIGHT", x = 1, y = 0 },
		["Debuff14"] = { point = "LEFT", relativeto = "Debuff13", relativepoint = "RIGHT", x = 1, y = 0 },
		["Debuff15"] = { point = "LEFT", relativeto = "Debuff14", relativepoint = "RIGHT", x = 1, y = 0 },
		["Debuff16"] = { point = "LEFT", relativeto = "Debuff15", relativepoint = "RIGHT", x = 1, y = 0 },
		["Buff1"] = { point = "TOPLEFT", relativeto = "Debuff1", relativepoint = "BOTTOMLEFT", x = 0, y = -2 },
		["Buff2"] = { point = "LEFT", relativeto = "Buff1", relativepoint = "RIGHT", x = 1, y = 0 },
		["Buff3"] = { point = "LEFT", relativeto = "Buff2", relativepoint = "RIGHT", x = 1, y = 0 },
		["Buff4"] = { point = "LEFT", relativeto = "Buff3", relativepoint = "RIGHT", x = 1, y = 0 },
		["Buff5"] = { point = "LEFT", relativeto = "Buff4", relativepoint = "RIGHT", x = 1, y = 0 },
		["Buff6"] = { point = "LEFT", relativeto = "Buff5", relativepoint = "RIGHT", x = 1, y = 0 },
		["Buff7"] = { point = "LEFT", relativeto = "Buff6", relativepoint = "RIGHT", x = 1, y = 0 },
		["Buff8"] = { point = "LEFT", relativeto = "Buff7", relativepoint = "RIGHT", x = 1, y = 0 },
	},
};