function LocalizeEN() 
	TITAN_DEBUG = "<Titan>";
	TITAN_INFO = "<Titan>"
	
	TITAN_NA = "N/A";
	TITAN_SECONDS = "seconds";
	TITAN_MINUTES = "minutes";
	TITAN_HOURS = "hours";
	TITAN_DAYS = "days";
	TITAN_SECONDS_ABBR = "s";
	TITAN_MINUTES_ABBR = "m";
	TITAN_HOURS_ABBR = "h";
	TITAN_DAYS_ABBR = "d";
	TITAN_MILLISECOND = "ms";
	TITAN_KILOBYTES_PER_SECOND = "KB/s";
	TITAN_KILOBITS_PER_SECOND = "kbps"
	TITAN_MEGABYTE = "MB";
	
	TITAN_MOVABLE_TOOLTIP = "Drag to move around";
	
	TITAN_PANEL = "Titan Panel";
	TITAN_PANEL_MENU_TITLE = "Titan Panel";
	TITAN_PANEL_MENU_HIDE = "Hide";
	TITAN_PANEL_MENU_CUSTOMIZE = "Customize";
	TITAN_PANEL_MENU_SHOW_COLORED_TEXT = "Show colored text";
	TITAN_PANEL_MENU_SHOW_ICON = "Show icon";
	TITAN_PANEL_MENU_SHOW_LABEL_TEXT = "Show label text";
	TITAN_PANEL_MENU_AUTOHIDE = "Auto-hide";
	TITAN_PANEL_MENU_CENTER_TEXT = "Center text";
	TITAN_PANEL_MENU_DISPLAY_ONTOP = "Display on top";
	TITAN_PANEL_MENU_BUILTINS = "Titan Built-ins";
	TITAN_PANEL_MENU_LEFT_SIDE = "Left Side";
	TITAN_PANEL_MENU_RIGHT_SIDE = "Right Side";
	
	TITAN_AUTOHIDE_TOOLTIP = "Toggles panel auto-hide on/off";
	TITAN_AUTOHIDE_MENU_TEXT = "Auto-hide";
	
	TITAN_AMMO_FORMAT = "%d";
	TITAN_AMMO_BUTTON_LABEL_AMMO = "Ammo: ";
	TITAN_AMMO_BUTTON_LABEL_THROWN = "Thrown: ";
	TITAN_AMMO_BUTTON_LABEL_AMMO_THROWN = "Ammo/Thrown: ";
	TITAN_AMMO_TOOLTIP = "Equipped Ammo/Thrown Count";
	TITAN_AMMO_MENU_TEXT = "Ammo/Thrown";
	TITAN_AMMO_THROWN_KEYWORD = "Throw";
	
	TITAN_BAG_FORMAT = "%d/%d";
	TITAN_BAG_BUTTON_LABEL = "Bags: ";
	TITAN_BAG_TOOLTIP = "Bag Usage";
	TITAN_BAG_TOOLTIP_HINTS = "Hint: Left-click to open all bags.";
	TITAN_BAG_MENU_TEXT = "Bag";
	TITAN_BAG_MENU_SHOW_USED_SLOTS = "Show used slots";
	TITAN_BAG_MENU_SHOW_AVAILABLE_SLOTS = "Show available slots";
	TITAN_BAG_MENU_IGNORE_AMMO_POUCH_SLOTS = "Ignore ammo pouch slots";
	TITAN_BAG_AMMO_POUCH_NAMES = {"Ammo", "Quiver", "Bandolier", "Shot"};
	
	TITAN_CLOCK_TOOLTIP = "Clock";
	TITAN_CLOCK_TOOLTIP_VALUE = "Offset hour value: ";
	TITAN_CLOCK_TOOLTIP_HINT1 = "Hint: Left-click to adjust the offset"
	TITAN_CLOCK_TOOLTIP_HINT2 = "hour and the 12/24H time format.";
	TITAN_CLOCK_CONTROL_TOOLTIP = "Hour Offset: ";
	TITAN_CLOCK_CONTROL_TITLE = "Offset";
	TITAN_CLOCK_CONTROL_HIGH = "+12";
	TITAN_CLOCK_CONTROL_LOW = "-12";
	TITAN_CLOCK_CHECKBUTTON = "24H Fmt";
	TITAN_CLOCK_CHECKBUTTON_TOOLTIP = "Toggles the time display between 12-hour and 24-hour format";
	TITAN_CLOCK_MENU_TEXT = "Clock";
	TITAN_CLOCK_MENU_DISPLAY_ON_RIGHT_SIDE = "Display on far right side";
	
	TITAN_COORDS_FORMAT = "(%.d, %.d)";
	TITAN_COORDS_BUTTON_LABEL = "Loc: ";
	TITAN_COORDS_TOOLTIP = "Location Info";
	TITAN_COORDS_TOOLTIP_HINTS_1 = "Hint: Shift + left-click to add location";
	TITAN_COORDS_TOOLTIP_HINTS_2 = "info to the chat message.";
	TITAN_COORDS_TOOLTIP_ZONE = "Zone: ";
	TITAN_COORDS_TOOLTIP_SUBZONE = "SubZone: ";
	TITAN_COORDS_TOOLTIP_PVPINFO = "PVP Info: ";
	TITAN_COORDS_TOOLTIP_HOMELOCATION = "Home Location";
	TITAN_COORDS_TOOLTIP_INN = "Inn: ";
	TITAN_COORDS_MENU_TEXT = "Location";
	TITAN_COORDS_MENU_SHOW_ZONE_ON_PANEL_TEXT = "Show zone text";
	TITAN_COORDS_MENU_SHOW_COORDS_ON_MAP_TEXT = "Show coordinates on world map";
	TITAN_COORDS_MAP_COORDS_TEXT = "%d, %d";
	TITAN_COORDS_MAP_CURSOR_COORDS_TEXT = "Cursor(X,Y): %s";
	TITAN_COORDS_MAP_PLAYER_COORDS_TEXT = "Player(X,Y): %s";
	
	TITAN_FPS_FORMAT = "%.1f";
	TITAN_FPS_BUTTON_LABEL = "FPS: ";
	TITAN_FPS_MENU_TEXT = "FPS";
	TITAN_FPS_TOOLTIP_CURRENT_FPS = "Current FPS: ";
	TITAN_FPS_TOOLTIP_AVG_FPS = "Average FPS: ";
	TITAN_FPS_TOOLTIP_MIN_FPS = "Minimum FPS: ";
	TITAN_FPS_TOOLTIP_MAX_FPS = "Maximum FPS: ";
	TITAN_FPS_TOOLTIP = "Frames Per Second";
	
	TITAN_HONOR_BUTTON_LABEL_RANK = RANK..": ";
	TITAN_HONOR_BUTTON_LABEL_HK = "HK: ";
	TITAN_HONOR_BUTTON_LABEL_DK = "DK: ";
	TITAN_HONOR_TOOLTIP = "PVP Honor Info";
	TITAN_HONOR_MENU_TEXT = "PVP Honor";
	
	TITAN_LATENCY_FORMAT = "%d"..TITAN_MILLISECOND;
	TITAN_LATENCY_BANDWIDTH_FORMAT = "%.3f "..TITAN_KILOBYTES_PER_SECOND;
	TITAN_LATENCY_BUTTON_LABEL = "Latency: ";
	TITAN_LATENCY_TOOLTIP = "Network Status";
	TITAN_LATENCY_TOOLTIP_LATENCY = "Latency: ";
	TITAN_LATENCY_TOOLTIP_BANDWIDTH_IN = "Bandwidth in: ";
	TITAN_LATENCY_TOOLTIP_BANDWIDTH_OUT = "Bandwidth out: ";
	TITAN_LATENCY_MENU_TEXT = "Latency";
	
	TITAN_LOOTTYPE_BUTTON_LABEL = "Loot: ";
	TITAN_LOOTTYPE_FREE_FOR_ALL = "Free for all";
	TITAN_LOOTTYPE_ROUND_ROBIN = "Round robin";
	TITAN_LOOTTYPE_MASTER_LOOTER = "Master looter";
	TITAN_LOOTTYPE_GROUP_LOOT = "Group Loot";
	TITAN_LOOTTYPE_NEED_BEFORE_GREED = "Need Before Greed";
	TITAN_LOOTTYPE_TOOLTIP = "Loot Type";
	TITAN_LOOTTYPE_MENU_TEXT = "Loot Type";
	
	TITAN_MEMORY_FORMAT = "%.3f"..TITAN_MEGABYTE;
	TITAN_MEMORY_RATE_FORMAT = "%.3f"..TITAN_KILOBYTES_PER_SECOND;
	TITAN_MEMORY_BUTTON_LABEL = "Memory: ";
	TITAN_MEMORY_TOOLTIP = "Memory Usage";
	TITAN_MEMORY_TOOLTIP_CURRENT_MEMORY = "Current: ";
	TITAN_MEMORY_TOOLTIP_INITIAL_MEMORY = "Initial: ";
	TITAN_MEMORY_TOOLTIP_INCREASING_RATE = "Increasing rate: ";
	TITAN_MEMORY_TOOLTIP_GC_INFO = "Garbage-Collection Info: ";
	TITAN_MEMORY_TOOLTIP_GC_THRESHOLD = "GC threshold: ";
	TITAN_MEMORY_TOOLTIP_TIME_TO_GC = "Time to next GC: "
	TITAN_MEMORY_MENU_TEXT = "Memory";
	TITAN_MEMORY_MENU_RESET_SESSION = "Reset memory data";
	
	TITAN_MONEY_GOLD = "g";
	TITAN_MONEY_SILVER = "s";
	TITAN_MONEY_COPPER = "c";
	TITAN_MONEY_FORMAT = "%d"..TITAN_MONEY_GOLD..", %d"..TITAN_MONEY_SILVER..", %d"..TITAN_MONEY_COPPER;
	TITAN_MONEY_MENU_TEXT = "Money";
	TITAN_MONEY_MENU_RESET_SESSION = "Reset session";
	TITAN_MONEY_TOOLTIP = "Money Fluctuation";
	TITAN_MONEY_TOOLTIP_HINTS = "Hint: Left-click to pick up money.";
	TITAN_MONEY_TOOLTIP_CURRENT = "Current: ";
	TITAN_MONEY_TOOLTIP_INITIAL = "Initial: ";
	TITAN_MONEY_TOOLTIP_EARNED = "Earned: ";
	TITAN_MONEY_TOOLTIP_LOST = "Lost: ";
	TITAN_MONEY_TOOLTIP_EARNED_HOUR = "Earned/hr: ";
	TITAN_MONEY_TOOLTIP_LOST_HOUR = "Lost/hr: ";
	
	TITAN_PERFORMANCE_TOOLTIP = "Performance";
	TITAN_PERFORMANCE_MENU_TEXT = "Performance";
	TITAN_PERFORMANCE_MENU_SHOW_FPS = "Show FPS";
	TITAN_PERFORMANCE_MENU_SHOW_LATENCY = "Show Latency";
	TITAN_PERFORMANCE_MENU_SHOW_MEMORY = "Show Memory";

	TITAN_TRANS_TOOLTIP = "Transparency Control";
	TITAN_TRANS_TOOLTIP_VALUE = "Panel transparency: ";
	TITAN_TRANS_TOOLTIP_HINT1 = "Hint: Left-click to adjust the";
	TITAN_TRANS_TOOLTIP_HINT2 = "transparency of the panel.";
	TITAN_TRANS_CONTROL_TOOLTIP = "Panel Transparency: ";
	TITAN_TRANS_CONTROL_TITLE = "Transparency";
	TITAN_TRANS_CONTROL_HIGH = "100%";
	TITAN_TRANS_CONTROL_LOW = "0%";
	TITAN_TRANS_MENU_TEXT = "Panel Transparency";
	
	TITAN_UISCALE_TOOLTIP = "UI/Panel Scale";
	TITAN_UISCALE_TOOLTIP_VALUE_UI = "UI Scale: ";
	TITAN_UISCALE_TOOLTIP_VALUE_PANEL = "Panel Scale: ";
	TITAN_UISCALE_TOOLTIP_HINT1 = "Hint: Left-click to adjusts the size of";
	TITAN_UISCALE_TOOLTIP_HINT2 = "the panel or game's user interface.";
	TITAN_UISCALE_CONTROL_TOOLTIP_UI = "UI Scale: ";
	TITAN_UISCALE_CONTROL_TOOLTIP_PANEL = "Panel Scale: ";
	TITAN_UISCALE_CONTROL_TITLE_UI = "UI Scale";
	TITAN_UISCALE_CONTROL_TITLE_PANEL = "Panel Scale";
	TITAN_UISCALE_CONTROL_HIGH_UI = "100%";
	TITAN_UISCALE_CONTROL_HIGH_PANEL = "125%";
	TITAN_UISCALE_CONTROL_LOW_UI = "64%";
	TITAN_UISCALE_CONTROL_LOW_PANEL = "75%";
	TITAN_UISCALE_MENU_TEXT = "UI/Panel Scale";
	
	TITAN_VOLUME_TOOLTIP = "Volume Control";
	TITAN_VOLUME_TOOLTIP_VALUE = "Master sound volume: ";
	TITAN_VOLUME_TOOLTIP_HINT1 = "Hint: Left-click to adjust the"
	TITAN_VOLUME_TOOLTIP_HINT2 = "master sound volume.";
	TITAN_VOLUME_CONTROL_TOOLTIP = "Master Sound Volume: ";
	TITAN_VOLUME_CONTROL_TITLE = "Volume";
	TITAN_VOLUME_CONTROL_HIGH = "High";
	TITAN_VOLUME_CONTROL_LOW = "Low";
	TITAN_VOLUME_MENU_TEXT = "Volume";
	
	TITAN_XP_FORMAT = "%d";
	TITAN_XP_PERCENT_FORMAT = TITAN_XP_FORMAT.." (%.1f%%)";
	TITAN_XP_BUTTON_LABEL_XPHR_LEVEL = "XP/hr this level: ";
	TITAN_XP_BUTTON_LABEL_XPHR_SESSION = "XP/hr this session: ";
	TITAN_XP_BUTTON_LABEL_TOLEVEL_TIME_LEVEL = "Time to level: ";
	TITAN_XP_BUTTON_LABEL_TOLEVEL_TIME_SESSION = "Time to level: ";
	TITAN_XP_TOOLTIP = "Experience(XP) Info";
	TITAN_XP_TOOLTIP_TOTAL_TIME = "Total time played: ";
	TITAN_XP_TOOLTIP_LEVEL_TIME = "Time played this level: ";
	TITAN_XP_TOOLTIP_SESSION_TIME = "Time played this session: ";
	TITAN_XP_TOOLTIP_TOTAL_XP = "Total XP required this level: ";
	TITAN_XP_TOOLTIP_LEVEL_XP = "XP gained this level: ";
	TITAN_XP_TOOLTIP_TOLEVEL_XP = "XP needed to level: ";
	TITAN_XP_TOOLTIP_SESSION_XP = "XP gained this session: ";
	TITAN_XP_TOOLTIP_XPHR_LEVEL = "XP/hr this level: ";
	TITAN_XP_TOOLTIP_XPHR_SESSION = "XP/hr this session: ";
	TITAN_XP_TOOLTIP_TOLEVEL_LEVEL = "Time to level (level rate): ";
	TITAN_XP_TOOLTIP_TOLEVEL_SESSION = "Time to level (session rate): ";
	TITAN_XP_MENU_TEXT = "Experience(XP)";
	TITAN_XP_MENU_SHOW_XPHR_THIS_LEVEL = "Show XP/hr this level";
	TITAN_XP_MENU_SHOW_XPHR_THIS_SESSION = "Show XP/hr this session";
	TITAN_XP_MENU_RESET_SESSION = "Reset session";
	
	TITAN_PLUGINS_MENU_TITLE = "Plug-ins";
	
	CUSTOMIZATION_FEATURE_COMING_SOON = "Customization feature coming soon...";
end

function Localize()
	LocalizeEN();

	-- Put all locale specific string adjustments here
	if ( GetLocale() == "deDE" ) then
		LocalizeDE();
	end
end

function LocalizeFrames()
	-- Put all locale specific UI adjustments here
end
