if ( GetLocale() == "frFR" ) then
CASTTIME = "CastTime"
CASTTIME_INFO = "Ces options contr\195\180lent le comportement de CastTime."
CASTTIME_DISPLAY_TOGGLE = "Activer CastTime"
CASTTIME_DISPLAY_TOGGLE_INFO = "Permet d\'afficher le temps restant d\'incantation sur la barre de cast."
CASTTIME_DELAY_TOGGLE = "Montrer les incantations interrompus"
CASTTIME_DELAY_TOGGLE_INFO = "Permet d\'afficher le temps restant d\'une incantation interrompue."
CASTTIME_HUN_TOGGLE = "Afficher les centi\195\168mes de secondes"
CASTTIME_HUN_TOGGLE_INFO = "Si d\195\169sactiv\195\169, les dizi\195\168mes de secondes ne sont qu\'affich\195\169es."
CASTTIME_FLOCK_TOGGLE = "V\195\169rouille et cache la fen\195\170tre"
CASTTIME_FLOCK_TOGGLE_INFO = "Ceci cachera la fen\195\170tre mobile et v\195\169rouillera sa position."
CASTTIME_MF_TOGGLE = "Utiliser la fen\195\170tre mobile "
CASTTIME_MF_TOGGLE_INFO = "Utilisation de la fen\195\170tre mobile au lieu du texte normal."

CASTTIME_IL_TOGGLE = "Utiliser CastTime inline"
CASTTIME_IL_TOGGLE_INFO = "Ceci affichera le temps restant \195\160 l\'int\195\169rieur de la barre de Cast."
CASTTIME_OL_TOGGLE = "Utiliser CastTime outline (Barre Traditionnelle)"
CASTTIME_OL_TOGGLE_INFO = "Ceci affichera le temps restant dans le coin droit au-dessus de la barre de Cast."

CASTTIME_MIRROR_TOGGLE = "Afficher les Timers auxiliaires"
CASTTIME_MIRROR_TOGGLE_INFO = "Ceci montrera le temps restant sur des Timers auxiliaires comme la fatigue, souffle et Feindre la mort."

CASTTIME_HELP1 = "Utilisation : D\195\169sactiver la visualisation, d\195\169sactive aussi le d\195\169lai lors d\'interruptions"
CASTTIME_HELP2 = " /castt stat"
CASTTIME_HELP3 = " /castt display [on|off]"
CASTTIME_HELP4 = " /castt inline [on|off]"
CASTTIME_HELP5 = " /castt outline [on|off]"
CASTTIME_HELP6 = " /castt delay [on|off]"
CASTTIME_HELP7 = " /castt hun [on|off]"
CASTTIME_HELP8 = " /castt lock [on|off]"
CASTTIME_HELP9 = " /castt frame [on|off]"
CASTTIME_HELP10 = " /castt mirror [on|off]"

CASTTIME_STATUS_DISPLAY = "L\'Affichage de la dur\195\169e est "
CASTTIME_STATUS_DELAY = "L\'Affichage du d\195\169lai d\'interruption est "
CASTTIME_STATUS_HUN = "L\'Affichage des centi\195\168mes de secondes est "
CASTTIME_STATUS_FLOCK = "Le V\195\169rrouillage de la fen\195\170tre mobile est "
CASTTIME_STATUS_MF = "L\'utilisation de la fen\195\170tre mobile est "

CASTTIME_STATUS_IL = "L\'Utilisation de Inline est "
CASTTIME_STATUS_OL = "L\'Utilisation de Outline est "
CASTTIME_STATUS_MIRROR = "L\'Utilisation des Timers auxiliaires est "

CASTTIME_ON = "on"
CASTTIME_OFF = "off"
CASTTIME_DISPLAY = "display"
CASTTIME_DELAY = "delay"
CASTTIME_HUN = "hun"
CASTTIME_FLOCK = "lock"
CASTTIME_STAT = "stat"
CASTTIME_MIRROR = "mirror"
CASTTIME_OL = "outline"
CASTTIME_IL = "inline"
CASTTIME_MF = "frame"
CASTTIME_MF_TOOLTIP = "Clic-Gauche pour d\195\169placer \la fen\195\170tre de CastTime."

end