--[[
Localisation file

]]

Perl_Description	= "Nymbia's Perl UnitFrames";
Perl_VersionNumber	= "1.1.7";
Perl_Version		= Perl_Description.." - Version "..Perl_VersionNumber;
PERL_LOC_CLASS_WARRIOR = "Warrior";
PERL_LOC_CLASS_MAGE = "Mage";
PERL_LOC_CLASS_ROGUE = "Rogue";
PERL_LOC_CLASS_DRUID = "Druid";
PERL_LOC_CLASS_HUNTER = "Hunter";
PERL_LOC_CLASS_SHAMAN = "Shaman";
PERL_LOC_CLASS_PRIEST = "Priest";
PERL_LOC_CLASS_WARLOCK = "Warlock";
PERL_LOC_CLASS_PALADIN = "Paladin";
PERL_LOC_TYPE_HUMANOID = "Humanoid";
PERL_LOC_TYPE_HUMANOID_LENGTH = 76
PERL_LOC_TYPE_BEAST = "Beast";
PERL_LOC_TYPE_BEAST_LENGTH = 60
PERL_LOC_TYPE_GIANT = "Giant";
PERL_LOC_TYPE_GIANT_LENGTH = 60
PERL_LOC_TYPE_UNDEAD = "Undead";
PERL_LOC_TYPE_UNDEAD_LENGTH = 60
PERL_LOC_TYPE_DEMON = "Demon";
PERL_LOC_TYPE_DEMON_LENGTH = 60
PERL_LOC_TYPE_ELEMENTAL = "Elemental";
PERL_LOC_TYPE_ELEMENTAL_LENGTH = 76
PERL_LOC_TYPE_CRITTER = "Critter";
PERL_LOC_TYPE_CRITTER_LENGTH = 60
PERL_LOC_TYPE_DRAGONKIN = "Dragonkin";
PERL_LOC_TYPE_DRAGONKIN_LENGTH = 76
if ( GetLocale() == "frFR" ) then
	PERL_LOC_CLASS_WARRIOR = "Guerrier";
	PERL_LOC_CLASS_MAGE = "Mage";
	PERL_LOC_CLASS_ROGUE = "Voleur";
	PERL_LOC_CLASS_DRUID = "Druide";
	PERL_LOC_CLASS_HUNTER = "Chasseur";
	PERL_LOC_CLASS_SHAMAN = "Chaman";
	PERL_LOC_CLASS_PRIEST = "Pr\195\170tre";
	PERL_LOC_CLASS_WARLOCK = "D\195\169moniste";
	PERL_LOC_CLASS_PALADIN = "Paladin";
	PERL_LOC_TYPE_HUMANOID = "Humano\195\175de";
	PERL_LOC_TYPE_HUMANOID = "Humano\195\175de";
	PERL_LOC_TYPE_BEAST = "B\195\170te";
	PERL_LOC_TYPE_GIANT = "G\195\169ant";
	PERL_LOC_TYPE_UNDEAD = "Mort-vivant";
	PERL_LOC_TYPE_DEMON = "D\195\169mon";
	PERL_LOC_TYPE_ELEMENTAL = "El\195\169mentaire";
	PERL_LOC_TYPE_CRITTER = "Bestiole";
	PERL_LOC_TYPE_DRAGONKIN = "Draconien";
end
if ( GetLocale() == "koKR" ) then
	PERL_LOC_CLASS_WARRIOR = "전사";
	PERL_LOC_CLASS_MAGE = "마법사";
	PERL_LOC_CLASS_ROGUE = "도적";
	PERL_LOC_CLASS_DRUID = "드루이드";
	PERL_LOC_CLASS_HUNTER = "사냥꾼";
	PERL_LOC_CLASS_SHAMAN = "주술사";
	PERL_LOC_CLASS_PRIEST = "사제";
	PERL_LOC_CLASS_WARLOCK = "흑마법사";
	PERL_LOC_CLASS_PALADIN = "성기사";
end
if ( GetLocale() == "deDE") then
	PERL_LOC_CLASS_WARRIOR = "Krieger";
	PERL_LOC_CLASS_MAGE = "Magier";
	PERL_LOC_CLASS_ROGUE = "Schurke";
	PERL_LOC_CLASS_DRUID = "Druide";
	PERL_LOC_CLASS_HUNTER = "J\195\164ger";
	PERL_LOC_CLASS_SHAMAN = "Schamane";
	PERL_LOC_CLASS_PRIEST = "Priester";
	PERL_LOC_CLASS_WARLOCK = "Hexenmeister";
	PERL_LOC_CLASS_PALADIN = "Paladin";
end