
EARTH_FEATURES_TITLE="Earth Feature Menu";

EARTHTREE_KEYWORD_TABLE="{Table}";
EARTHTREE_KEYWORD_BOOL_TRUE="|True|";
EARTHTREE_KEYWORD_BOOL_FALSE="|False|";
EARTHTREE_KEYWORD_FUNCTION="*Function*";
EARTHTREE_KEYWORD_NIL="nil";
EARTHTREE_KEYWORD_UNKNOWN="/Unknown Type/";

EARTHTREE_EXPAND_COLLAPSE="Expand/Collapse";
EARTHTREE_EXPAND_INFO="Children: ";

EARTHTABLE_KEYWORD_TABLE="{Table}";
EARTHTABLE_KEYWORD_FUNCTION="*Function*";
EARTHTABLE_KEYWORD_NIL="nil";
EARTHTABLE_KEYWORD_UNKNOWN="/Unknown/";
EARTHTABLE_KEYWORD_BOOL_TRUE="True";
EARTHTABLE_KEYWORD_BOOL_FALSE="False";

