-- Localization Strings

ServitudeProp = {};
ServitudeProp.Version = 050717.1;
ServitudeProp.Author = "Visionary and Graguk";
ServitudeProp.AppName = "Servitude";
ServitudeProp.Label = ServitudeProp.AppName .. " (v" .. ServitudeProp.Version .. ")";
ServitudeProp.LongLabel = ServitudeProp.Label .. " by " .. ServitudeProp.Author;
ServitudeProp.CleanLabel = ServitudeProp.AppName .. " by " .. ServitudeProp.Author;
ServitudeProp.Description = "A warlock pet addon that manages and autocasts your pet skills";

ServitudeConfigMenuTitle = ServitudeProp.Label;

VoidwalkerOptions = "Voidwalker Options";
ImpOptions = "Imp Options";
SuccubusOptions = "Succubus Options";
FelhunterOptions = "Felhunter Options";
GeneralOptions = "General Options";

InCombatDivider = "=== In/Out Combat Line ===";
SpellLockDivider = "=== Spell Lock ===";
ClassDivider = "=== Class Priority ===";
BuffDatabaseTitle = "Debuff Priority";
SpellDatabaseTitle = "Spell Lock";
ClassDatabaseTitle = "Class Priority";
FireShieldClassDatabaseTitle = "FS Class List";

BINDING_HEADER_SERVITUDE = "Servitude";
BINDING_NAME_DOSERVITUDEOPEN = "Open Servitude Config Panel";
BINDING_NAME_DOPRIMARY = "Cast Primary Pet Spell";
BINDING_NAME_DOSECONDARY = "Cast Secondary Pet Spell";

ConfigObjectText =
{
	VWAutoShadow = "Alert Consume Shadows";
	VWAutoShadowRatio = "Consume Shadows Percent";
	VWAutoTaunt = "Smart Torment";
	VWAutoTauntRatio = "Smart Torment Percent";
	VWAutoSacrif = "Alert Sacrifice";
	VWAutoSacrifCombat = "In Combat Only";
	VWAutoTauntBanish = "No Taunt if Banished";
	VWAutoSacrifPetRatio = "Sacrifice Percent for Pet";
	VWAutoSacrifPlayerRatio = "Sacrifice Percent for Player";
	VWSacrificeAlert = "Vocal Sacrifice Alert";

	ImpSmartFireshield = "Smart Fire Shield - Party/Raid";
	ImpSmartFireshieldNeutral = "Disable in Neutral Towns";
	ImpSmartFireshieldSolo = "Smart Fire Shield - Solo";
	ImpSmartFireshieldAlways = "Smart Fire Shield Always";
	ImpSmartFirebolt = "Smart Firebolt";
	ImpFireboltDisable = "Disable Firebolt After Combat";
	ImpSmartFireboltRatio = "Min Mana for Firebolt";
	ImpFireShieldAlert = "Fire Shield Alert";
	
	ScbSmartSooth = "Smart Soothing Kiss";
	ScbSmartSoothRatio = "Soothing Kiss Percent";
	ScbAutoInvisib = "Alert Invisibility";
	ScbAutoInvisibManaRatio = "Min Mana for Invis";
	ScbInvisDelay = "Delay Invis post Combat";
--	ScbSeduceFollow = "Follow on Seduce break";
	ScbSeduceCOS = "CoS on Seduce";
	ScbSeduceCOE = "CoE on Seduce";
	ScbSmartLOP = "Smart Lash of Pain";
	ScbSmartLOPRatio = "Min Mana for LoP";
--	ScbAlwaysSeduce = "Re-Seduce on break";
	ScbSeduceAlert = "Seduction Alert";
	ScbSeduceAnnounce = "Announce Seduction";

	FHNonCombatDevour = "Alert Non-Combat Devour";
	FHHungerDevour = "Hungry Felhunter";
	FHHungerDevourRatio = "Hunger Percent";
	FHPartyDevour = "Party Devour";
	FHDevourSelf = "Felhunter First";
	FHDevourPets = "Raid/Party Pets";
	FHDevourIgnoreSelf = "Ignore Felhunter";
	FHRaidDevour = "Raid Devour";
	FHDevourMindVision = "Devour Mind Vision";
	FHSpellLockPVP = "Spell Lock PVP";
	FHSpellLockPVE = "Spell Lock PVE";
	FHDisableNotification = "Disable Spell/Debuff Notification";
	FHClassAsPriority = "Devour by Class";
	FHPriorityUnitOnly = "Only Devour Priority Unit";
	FHDevourAlert = "Devour Magic Alert";
	FHSpellLockAlert = "Spell Lock Alert";
	
	OneButton = "One Button Pets";
	HealthWarning = "Pet Health Warning";
	HealthWarningRatio = "Pet Health Percentage";
	HealthWarningVocal = "Vocal Health Warning";
}

ConfigObjectTooltip =
{
	VWAutoShadow = "Alert player after battle if the Voidwalker's HP is below a specified percentage to cast Consume Shadows.";
	VWAutoSacrif = "Alert the player to Sacrifice the Voidwalker during battle if his or the player's HP drops below a specified percentage. (Note: Will not trigger if massive amount of damage is taken in short duration)";
	VWAutoSacrifCombat = "Sacrifice alert will only trigger if in combat.";
	VWAutoTauntBanish = "Auto-Taunt will disable if Voidwalker's target is banished.";
	VWAutoTaunt = "Voidwalker will stop casting Torment in battle after it's target's health drops below a specified percentage.";
	VWSacrificeAlert = "When the player or Voidwalker's health drops below the configured percent, a vocal alert will be played.";
	
	ImpSmartFireshield = "Imp will cast Fire Shield on tanking classes if in a Party/Raid.";
	ImpSmartFireshieldNeutral = "Imp will not Fire Shield when in Neutral cities. It will also cancel Fire Shield on the player in these locations.";
	ImpSmartFireshieldSolo = "Imp will cast Fire Shield on the Warlock if not in a Party/Raid.";
	ImpSmartFireshieldAlways = "Imp will cast Fire Shield on all party members if they are in range, regardless of Class.";
	ImpSmartFirebolt = "Imp will activate Auto-Cast on Firebolt while mana is above the configured slider.";
	ImpFireboltDisable = "Imp will disable Firebolt auto-cast after combat. Smart Firebolt will override this option.";
	ImpFireShieldAlert = "When the Imp detects a unit that needs a Fire Shield based on your configuration, a vocal alert will be played.";
	
	ScbSmartSooth = "Succubus will not cast Soothing Kiss if her HP is above a specified percentage.";
	ScbAutoInvisib = "Alert the player if the Succubus can cast Lesser Invisibility after battle if she has no debuff. Minimum Succubus Mana Slider for those who use Dark Pact.";
	ScbInvisDelay = "If checked, the Succubus will wait 10 seconds after combat finishes before Alerting the player that Invisibility is available - this allows for Dark Pact time.";
--	ScbSeduceFollow = "Succubus will follow the player after the target of seduction has been damaged, instead of attacking it.";
	ScbSmartLOP = "Succubus will enable auto-cast of Lash of Pain while her mana is above the configured percentage.";
--	ScbAlwaysSeduce = "Succubus will re-seduce even when the target is damaged. This option will override the Follow on Seduce Break option.";
	ScbSeduceAlert = "When the Succubus detects that Seduction has faded or been broken from an enemy, a vocal alert will be played.";
	ScbSeduceCOS = "When enabled, the player will cast Curse of Shadow on a target at the same time as commanding the Succubus to Seduce for the first time.";
	ScbSeduceCOE = "When enabled, the player will cast Curse of the Elements on a target at the same time as commanding the Succubus to Seduce for the first time. CoS on Seduce takes priority if enabled.";
	ScbSeduceAnnounce = "When enabled, the player will announce the initial seduction target to Party chat.";

	FHNonCombatDevour = "Felhunter will search and devour magical debuffs on himself or the player after battle.";
	FHHungerDevour = "Felhunter will search and devour magical debuffs on himself or the player during combat if his HP drop below a specified percentage.";
	FHPartyDevour = "Party support for Devour features";
	FHDevourSelf = "Devour the Felhunter before all others";
	FHDevourIgnoreSelf = "Never Devour the Felhunter. This option overrides Felhunter First.";
	FHRaidDevour = "Raid support for Devour features";
	FHDevourPets = "If enabled, this will scan raid and party pets if the corresponding Raid/Party scanning option is enabled.";
	FHDevourMindVision = "Mind Vision is often used by friendly players, but shows up as a Debuff. Select this option if you want to devour it anyway.";
	FHSpellLockPVP = "Spell Lock PVP targets if you are PVP flagged.";
	FHSpellLockPVE = "Spell Lock PVE targets. Can get confused if a unit with the same name as your target casts.";
	FHDisableNotification = "This option disables Servitude's notification of learning a new spell or debuff.";
	FHClassAsPriority = "When selected, the Class Priority database will be used to Devour classes in order of preference, rather than whether to ignore that class or not. (more CPU than default)";
	FHPriorityUnitOnly = "Auto-Devour will only scan debuffs on the stored Priority Unit. It will ignore all other raid and party members, including the player and Felhunter.";
	FHDevourAlert = "When the Felhunter detects a unit that needs to be Devoured based on your configuration, a vocal alert will be played.";
	FHSpellLockAlert = "When the Felhunter detects your target starts casting a spell you've told him to Spell Lock, a vocal alert will be played.";
	OneButton = "When enabled, Pet management can be executed with just the Primary Pet Button. The Secondary Pet Button will be used for Seduce/ReSeduce, and Devour Magic on your target.";
	HealthWarning = "When enabled, Servitude will alert you when your pet's health drops below the configured percentage.";
	HealthWarningVocal = "When your pet's health drops below the configured percentage, a vocal alert will be played.";
}

ServitudeChatMsg = 
{
	SoothingKissToggleError = "Soothing Kiss is currently being managed by Servitude. The game's autocast setting will be overwritten during combat.";
	LOPToggleError = "Lash of Pain is currently being managed by Servitude. The game's autocast setting will be overwritten.";
	AutoTauntToggleError = "Taunt is currently being managed by Servitude. The game's autocast setting will be overwritten during combat.";
	ImpSmartFireshieldToggleError = "Fire Shield is currently being managed by Servitude. The game's autocast setting will be overwritten on the next player scan.";
	ImpSmartFireboltToggleError = "Firebolt is currently being managed by Servitude. The game's autocast setting will be overwritten.";
	FHSpellLockToggleError = "Spell Lock is currently being managed by Servitude. The game's autocast setting will be overwritten in combat.";
	LoadDefault = "Loaded default configuration.";
	ObjectLoadFail = "Error! Failed to load object:";
	ObjectSaveFail = "Error! Failed to save object:";
	WelcomeMsg = ServitudeProp.CleanLabel .. " for fellow warlocks (Slash commands: /servitude help or /serv help)";
	NewDebuffObserved = "New magical debuff has been observed:";
	NewSpellObserved = "New Spell has been observed:";
	DebuffDatabaseCorrupted = "Debuff database is corrupted or empty and has been purged. Default Database loaded.";
	SpellDatabaseCorrupted = "Spell Lock database is corrupted or empty. Database cleared.";
	ClassDatabaseCorrupted = "Class Database is corrupted or empty. Default Database loaded.";
	FireShieldClassDatabaseCorrupted = "Fire Shield Class Database is corrupted or empty. Default Database loaded.";
	DebuffDatabaseVerified = "Debuff database entry count:";
	SpellDatabaseVerified = "Spell Lock database entry count:";
}

ServitudeNotificationMsg =
{
	InvisNotification = "Lesser Invisibility (Primary)";
	SpellLockPVP = "Spell Lock! (Secondary)";
	SpellLockPVE = "Spell Lock! (Secondary)";
	SeductionNotification = "Re-Seduce NOW! (Secondary)";
	Sacrifice = "Sacrifice NOW! (Secondary)";
	ConsumeShadows = "Consume Shadows (Primary)";
	DebuffsDetected = "Devour NOW! (Primary)";
	FireShieldRequired = "Fire Shield! (Primary)";
	ServitudeAlertTest = "This is a test. Move this frame to the area that you can see best.";
	HealthLow = "Your Pet is DYING!";
}

DE_Magical_Debuff_List = {
	["Feuerbrand"] = "Alle 3 Sekunden 73 Punkte Feuerschaden.",
	["Nachwirkung"] = "Bewegung um 50% verlangsamt.",
	["Blackout"] = "Ohnmächtig.",
	["Verwandlung"] = "Kann weder angreifen noch Zauber wirken. Erhöhte Regeneration.",
	["Schreckliches Kreischen"] = "Flüchtet voller Furcht.",
	["Kälte"] = "Bewegung verlangsamt auf 70% und Angriffstempo verlangsamt um 20%.",
	["Frostschock"] = "Bewegung auf 50% des normalen Tempos verlangsamt.",
	["Heiliges Feuer"] = "Alle 2 Sek. Feuerschaden zugefügt.",
	["Jäger-Mal"] = "Alle Angreifer erhalten 20 Distanzangriffskraft gegenüber diesem Ziel.",
	["Frostfalle-Effekt"] = "Bewegung auf 40% des normalen Tempos verlangsamt.",
	["Verderbnis"] = "Alle 3 Sekunden 74 Punkte Schaden.",
	["Blitzeis"] = "Betäubt.",
	["Frostnova"] = "Festgefroren.",
	["Schallexplosion"] = "Zauber wirken nicht möglich.",
	["Mana entziehen"] = "Entzieht jede Sekunde 140 Punkte Mana für den Zaubernden.",
	["Mondfeuer"] = "Alle 3 Sekunden 53 Punkt(e) Arkanschaden.",
	["Verlangsamen"] = "Angriffstempo um 35% verringert. Bewegungstempo auf 40% des normalen Tempos verlangsamt.",
	["Winterschlaf"] = "Schlafend.",
	["Donnerknall"] = "Angriffstempo um 25% verringert. Bewegungstempo auf 45% des normalen Tempos verlangsamt.",
	["Gebrechlichkeit"] = "Alle Attribute um 30 verringert.",
	["Wahnsinn verursachen"] = "Bezaubert. Angriffstempo um 50% erhöht. Bewegungstempo um 80% erhöht.",
	["Erschrecken"] = "Flüchtet voller Furcht.",
	["Richturteil der Weisheit"] = "Angriffe und Zauber gegen Euch haben eine Chance beim Angreifer 59 Mana wiederherzustellen.",
	["Flammenschock"] = "Fügt alle 3 Sekunden Feuerschaden zu.",
	["Erdbindung"] = "Bewegung auf 50% des normalen Tempos verringert.",
	["Erschütternder Schuss"] = "Bewegung auf 50% des normalen Tempos verlangsamt.",
	["Kältekegel"] = "Bewegung auf 50% verlangsamt.",
	["Verbannen"] = "Unverwundbar, aber kann nicht agieren.",
	["Besudeltes Blut’ - Effekt"] = "Angriffskraft verringert um 200,",
	["Tritt - zum Schweigen gebracht"] = "Zum Schweigen gebracht.",
	["Frostschuss"] = "Bewegungstempo auf 40% des normalen Tempos verlangsamt.",
	["Entkräftende Berührung"] = "Stärke um 20 verringert. Ausdauer um 20 verringert.",
	["Tod durch Ertrinken"] = "Schwimmtempo um 20% verringert. Beweglichkeit um 15% verringert.",
	["Gegenzauber - zum Schweigen gebracht"] = "Zum Schweigen gebracht.",
	["Schattenverwundbarkeit"] = "Schattenschaden um 20% erhöht.",
	["Spitelash"] = "Erlittener körperlicher Schaden um 43 bis 57 Punkt(e) erhöht.",
	["Eiskältefalle-Effekt"] = "Eingefroren.",
	["Welkstoß"] = "Angriffstempo um 33% verringert.",
	["Richturteil des Kreuzfahrers"] = "Erhöht erlittenen Heiligschaden um bis zu 140,",
	["Blutsauger"] = "Entzieht pro Sekunde 71 Punkte Gesundheit und überträgt sie auf den Zaubernden.",
	["Hammer der Gerechtigkeit"] = "Betäubt.",
	["Schattenwort: Schmerz"] = "142 Punkte Schattenschaden alle 3 Sekunden.",
	["Traumloser Schlaf"] = "Traumloser Schlaf.",
	["Richturteil des Lichts"] = "Nahkampfangriffe gegen Euch haben eine Chance, dass der Angreifer um 49 geheilt wird.",
	["Schreckgeheul"] = "Flüchtet vor Schreck.",
	["Feenfeuer"] = "Verringert Rüstung um 285, Kann weder Verstohlenheit anwenden noch unsichtbar werden.",
	["Flammenpuffer"] = "Erlittener Feuerschaden um 246 Punkt(e) erhöht.",
	["Wucherwurzeln"] = "Eingewurzelt. Verursacht alle 3 Sekunden 30 Punkte Schaden.",
	["Sprengfalle’-Effekt"] = "Alle 2 Sekunden 33 Punkt(e) Feuerschaden.",
	["Lebensentzug"] = "Zieht alle 3 Sek. 45 Punkt(e) Gesundheit auf den Zaubernden ab.",
	["Erfrierung"] = "Eingefroren.",
	["Furcht"] = "Furchterfüllt.",
	["Untote fesseln"] = "Gefesselt.",
	["Verhexung"] = "Verhext.",
	["Besudeltes Blut' - Effekt"] = "Angriffskraft verringert um 40.",
	["Frostblitz"] = "Bewegung auf 50% verlangsamt.",
	["Verführung"] = "Verführt.",
	["Dämon zerschmettern"] = "Betäubt.",
	["Stille"] = "Zum Schweigen gebracht.",
	["Verkrüppeln"] = "Bewegungstempo auf 50% des normalen Tempos verlangsamt. Angriffstempo um 50% verringert. Stärke um 50% verringert.",
}

DE_Devour_Order = {
	[1] = "Stille",
	[2] = "Verwandlung",
	[3] = "Schattenwort: Schmerz",
	[4] = "Hammer der Gerechtigkeit",
	[5] = "Mondfeuer",
	[6] = "Feuerbrand",
	[7] = "Verderbnis",
	[8] = "Frostschock",
	[9] = "Erdbindung",
	[10] = "Furcht",
	[11] = "Schattenverwundbarkeit",
	[12] = "Erschütternder Schuss",
	[13] = "Frostblitz",
	[14] = "Verbannen",
	[15] = "Jäger-Mal",
	[16] = "Verführung",
	[17] = "Wucherwurzeln",
	[18] = "Frostnova",
	[19] = "Blackout",
	[20] = "Besudeltes Blut' - Effekt",
	[21] = "Richturteil des Lichts",
	[22] = "Lebensentzug",
	[23] = "Blutsauger",
	[24] = "Mana entziehen",
	[25] = "Feenfeuer",
	[26] = "Flammenschock",
	[27] = "Heiliges Feuer",
	[28] = "Schreckgeheul",
	[29] = "Traumloser Schlaf",
	[30] = "Erfrierung",
	[31] = "Gegenzauber - zum Schweigen gebracht",
	[32] = "Erschrecken",
	[33] = "Spitelash",
	[34] = "Frostschuss",
	[35] = "Kältekegel",
	[36] = "Tritt - zum Schweigen gebracht",
	[37] = "Donnerknall",
	[38] = "Kälte",
	[39] = "Eiskältefalle-Effekt",
	[40] = "Gebrechlichkeit",
	[41] = "Schallexplosion",
	[42] = "Frostfalle-Effekt",
	[43] = "Nachwirkung",
	[44] = "Flammenpuffer",
	[45] = "Untote fesseln",
	[46] = "Wahnsinn verursachen",
	[47] = "Verkrüppeln",
	[48] = "Richturteil des Kreuzfahrers",
	[49] = "Dämon zerschmettern",
	[50] = "Schreckliches Kreischen",
	[51] = "Welkstoß",
	[52] = "Besudeltes Blut’ - Effekt",
	[53] = "Sprengfalle’-Effekt",
	[54] = "Blitzeis",
	[55] = "Verlangsamen",
	[56] = "Entkräftende Berührung",
	[57] = "Verhexung",
	[58] = "Richturteil der Weisheit",
	[59] = "Winterschlaf",
	[60] = "Tod durch Ertrinken",
	[61] = "=== In/Out Combat Line ===",
}

DE_Spell_Lock_List = {
	["Vipernbiss"] = "Observed",
	["Verwandlung"] = "Observed",
	["Schlangenbiss"] = "Observed",
	["Blutfluch"] = "Observed",
	["Manabrand"] = "Observed",
	["Giftwolke"] = "Observed",
	["Erneuerung"] = "Observed",
	["Atal’ai-Skelett beschwören"] = "Observed",
	["Tiefer Schlummer"] = "Observed",
	["Flammenschauer"] = "Observed",
	["Gedankenschlag"] = "Observed",
	["Arkaner Schuss"] = "Observed",
	["Geringe Welle der Heilung"] = "Observed",
	["Nachwachsen"] = "Observed",
	["Schattenblitz-Salve"] = "Observed",
	["Kettenblitzschlag"] = "Observed",
	["Annalen von Darrowshire’ verzaubern"] = "Observed",
	["Furcht"] = "Observed",
	["Dunkle Besserung"] = "Observed",
	["Heilende Berührung"] = "Observed",
	["Heilen"] = "Observed",
	["Feuerblitz"] = "Observed",
	["Flammenpuffer"] = "Observed",
	["Wucherwurzeln"] = "Observed",
	["Angreifen"] = "Observed",
	["Flammenstachel"] = "Observed",
	["Schlachtross beschwören"] = "Observed",
	["Gruftskarabäen"] = "Observed",
	["Heilungs-Zauberschutz"] = "Observed",
	["Sengender Schmerz"] = "Observed",
	["Pyroschlag"] = "Observed",
	["Geisterwolf"] = "Observed",
	["Säurespucke"] = "Observed",
	["Zorn"] = "Observed",
	["Verkrüppeln"] = "Observed",
	["Erschütternder Schuss"] = "Observed",
	["Schattenblitz"] = "Observed",
	["Schneller Flammen-Zauberschutz"] = "Observed",
	["Feuerschild II"] = "Observed",
	["Echsenschlag"] = "Observed",
	["Augen des Wildtiers"] = "Observed",
	["Blitzschlag"] = "Observed",
	["Flammenatem"] = "Observed",
	["Feuerbrand"] = "Observed",
	["Streuschuss"] = "Observed",
	["Atal'ai-Skelett beschwören"] = "Observed",
	["Erdengriff-Totem"] = "Observed",
	["Skorpidstich"] = "Observed",
	["Feuerball"] = "Observed",
	["Banshee-Fluch"] = "Observed",
	["Schattenschuss"] = "Observed",
	["Mana-Citrin herbeizaubern"] = "Observed",
	["Arkanblitz"] = "Observed",
	["Schlaf"] = "Observed",
	["Arkane Explosion"] = "Observed",
	["Frostblitz-Salve"] = "Observed",
	["Große Heilung"] = "Observed",
	["Flammenstoß"] = "Observed",
	["Gezielter Schuss"] = "Observed",
	["Untote fesseln"] = "Observed",
	["Schreckgeheul"] = "Observed",
	["Ruhestein"] = "Observed",
	["Frostblitz"] = "Observed",
	["Welle der Heilung"] = "Observed",
	["Versengen"] = "Observed",
	["Toxin-Speichel"] = "Observed",
	["Blitzheilung"] = "Observed",
}

DE_Spell_Lock_Order = {
	[1] = "Wucherwurzeln",
	[2] = "Zorn",
	[3] = "Gedankenschlag",
	[4] = "Schattenblitz-Salve",
	[5] = "Manabrand",
	[6] = "Schattenblitz",
	[7] = "Arkaner Schuss",
	[8] = "Schlangenbiss",
	[9] = "Dunkle Besserung",
	[10] = "Frostblitz",
	[11] = "Feuerball",
	[12] = "Toxin-Speichel",
	[13] = "Mana-Citrin herbeizaubern",
	[14] = "=== Spell Lock ===",
	[15] = "Angreifen",
	[16] = "Kettenblitzschlag",
	[17] = "Blitzschlag",
	[18] = "Arkane Explosion",
	[19] = "Heilende Berührung",
	[20] = "Blitzheilung",
	[21] = "Geringe Welle der Heilung",
	[22] = "Pyroschlag",
	[23] = "Welle der Heilung",
	[24] = "Flammenstoß",
	[25] = "Geisterwolf",
	[26] = "Feuerbrand",
	[27] = "Erschütternder Schuss",
	[28] = "Vipernbiss",
	[29] = "Skorpidstich",
	[30] = "Blutfluch",
	[31] = "Säurespucke",
	[32] = "Streuschuss",
	[33] = "Flammenpuffer",
	[34] = "Flammenschauer",
	[35] = "Flammenatem",
	[36] = "Untote fesseln",
	[37] = "Schlaf",
	[38] = "Verwandlung",
	[39] = "Atal'ai-Skelett beschwören",
	[40] = "Feuerblitz",
	[41] = "Giftwolke",
	[42] = "Furcht",
	[43] = "Heilen",
	[44] = "Tiefer Schlummer",
	[45] = "Gezielter Schuss",
	[46] = "Versengen",
	[47] = "Schlachtross beschwören",
	[48] = "Sengender Schmerz",
	[49] = "Echsenschlag",
	[50] = "Große Heilung",
	[51] = "Augen des Wildtiers",
	[52] = "Ruhestein",
	[53] = "Atal’ai-Skelett beschwören",
	[54] = "Heilungs-Zauberschutz",
	[55] = "Erneuerung",
	[56] = "Erdengriff-Totem",
	[57] = "Frostblitz-Salve",
	[58] = "Banshee-Fluch",
	[59] = "Arkanblitz",
	[60] = "Nachwachsen",
	[61] = "Schattenschuss",
	[62] = "Gruftskarabäen",
	[63] = "Verkrüppeln",
	[64] = "Schreckgeheul",
	[65] = "Annalen von Darrowshire’ verzaubern",
	[66] = "Flammenstachel",
	[67] = "Feuerschild II",
	[68] = "Schneller Flammen-Zauberschutz",
}

DE_Class_Order = {
				[1] = "Druide",
				[2] = "Jäger",
				[3] = "Magier",
				[4] = "Paladin",
				[5] = "Priester",
				[6] = "Schurke",
				[7] = "Schamane",
				[8] = "Krieger",
				[9] = "Hexenmeister",
				[10] = "=== Class Priority ===",
}

FR_Magical_Debuff_List = {
	["Corruption"] = "54 points de dégâts d'ombre toutes les 3 secondes.",
	["Marque du chasseur"] = "Tous les attaquants gagnent 110 points de puissance d'attaque à distance contre cette cible.",
	["Nova de givre"] = "Immobilisé.",
	["Marteau de la justice"] = "Etourdi.",
	["Explosion sonore"] = "Ne peut pas lancer de sorts.",
	["Eclair de givre"] = "Mouvement réduit à 60 %.",
	["Drain de mana"] = "Le lanceur de sort draine 138 points de mana par seconde.",
	["Flammes sacrées"] = "Points de dégâts de Feu toutes les 2 sec.",
	["Torpeur"] = "Endormi.",
	["Métamorphose"] = "Ne peut pas attaquer ou lancer de sorts. Vitesse de récupération des points de vie augmentée.",
	["Frappe fantôme"] = "Réduit l’armure de 100, Camouflage ou Invisibilité impossibles.",
	["Immolation"] = "73 dégâts de Feu toutes les 3 secondes.",
	["Rugissement glacial"] = "Assommée.",
	["Hurlement de terreur"] = "Fuit terrorisé.",
	["Acide corrosif"] = "Armure réduite de 736.",
	["Champignon de Mirefin"] = "Vitesse de déplacement réduite à 50% de la normale.",
	["Fragilité"] = "Toutes les caractéristiques sont réduites de 10,",
	["Faiblesse"] = "Vitesse de déplacement réduite à 50% de la normale. La vitesse d'attaque est réduite de 50%. La Force est réduite de 50%.",
	["Peur"] = "Apeuré.",
	["Bannir le Démon"] = "Etourdi.",
	["Sommeil cristallin"] = "Assommée.",
	["Effet Piège explosif"] = "33 points de dégâts de Feu toutes les 2 secondes.",
	["Détection de la magie"] = "Détection de la Magie.",
	["Pétrifier"] = "Assommé. Armure augmentée de 30%.",
	["Hex"] = "Sous l'effet de l'Hex.",
	["Rafale de flammes"] = "Les points de dégâts de Feu subis sont augmentés de 30,",
	["Gelé"] = "Vitesse d'attaque réduite de 20%. Vitesse de déplacement réduite à 70% de la normale.",
	["Bannir"] = "Invulnérable, mais incapable d'agir.",
	["Intimidation"] = "Fuit effrayé.",
	["Fouet malveillant"] = "Les points de dégâts physiques subis sont augmentés de 43 à 57.",
	["Trait de choc"] = "Vitesse de déplacement réduite à 50% de la normale.",
	["Aveuglement"] = "Aveuglé.",
	["Transi"] = "Mouvement réduit à 70 % et attaques réduites de 20 %.",
	["Hurlement terrifiant"] = "Fuit effrayé.",
	["Horion de givre"] = "Mouvement réduit à 50 % de la vitesse normale.",
	["Vulnérabilité au feu"] = "Augmente les dégâts de Feu subis de 4.",
	["Siphon de vie"] = "Draine 45 points de vie au lanceur de sorts toutes les 3 secs.",
	["Coup fané"] = "Vitesse d'attaque réduite de 33%.",
	["Silence"] = "Ne peut pas lancer de sorts.",
	["Bombe fumigène"] = "Assommée.",
	["Coupure d'ailes améliorée"] = "Immobilisé.",
	["Vision télépathique"] = "Vue par les yeux de la cible.",
	["Linceul de vents"] = "Assommée.",
	["Horion de flammes"] = "Dégâts de Feu toutes les 3 sec.",
	["Lenteur"] = "Vitesse d'attaque réduite de 35%. Vitesse de déplacement réduite à 40% de la normale.",
	["Jugement de justice"] = "Ne peut pas fuir.",
	["Effet Piège givrant"] = "Gelé.",
	["Sarments"] = "Enraciné. Inflige 25 points de dégâts toutes les 3 secondes.",
	["Coup de bouclier - silencieux"] = "Réduit au silence.",
	["Jugement d'autorité"] = "38 dégâts Sacrés subis lorsque étourdi.",
	["Geler sur place"] = "Assommé. 108 à 122 points de dégâts de givre infligés toutes les 3 sec.",
	["Effet Piège gelant"] = "Gelé.",
	["Drain de vie"] = "Le lanceur de sort draine 71 points de vie par seconde.",
	["Effet de Corruption sanguine"] = "Puissance d'attaque réduite de 120,",
	["Effrayer une bête"] = "Effrayé.",
	["Mot de l'ombre : Douleur"] = "Points de dégâts d'ombre infligés toutes les 3 sec.",
	["Fracas de vagues"] = "Assommée.",
	["Trait de glace"] = "Immobilisation.",
	["Lien à la terre"] = "Vitesse de déplacement réduite à 50% de la normale.",
	["Jugement de sagesse"] = "Les attaques et les sorts à votre encontre ont une chance de rendre 46 mana à l'attaquant.",
	["Rendre fou"] = "Charmé. Vitesse d'attaque augmentée de 50%. Vitesse de déplacement augmentée de 80%.",
	["Effet Piège immolation"] = "138 points de dégâts de Feu toutes les 3 secondes.",
	["Flèche de givre"] = "Vitesse de déplacement réduite à 40% de la normale.",
	["Cône de froid"] = "Mouvement réduit à 50 %.",
	["Conséquences"] = "Vitesse de déplacement réduite de 50%.",
	["Amplifier flammes"] = "Les points de dégâts de Feu subis sont augmentés de 100.",
	["Drainer la vie"] = "Le lanceur de sort draine 55 points de vie par seconde.",
	["Vulnérabilité à l'ombre"] = "Les points de dégâts d'ombre sont augmentés de 20%.",
	["Griffe de glace"] = "Vitesse d'attaque réduite de 50%.",
	["Jugement de lumière"] = "Les attaques de mêlée contre vous ont une chance de soigner l'attaquant pour 34,",
	["Jugement du Croisé"] = "Augmente les dégâts Sacrés subis de 110,",
	["Effet Piège de givre"] = "Vitesse de déplacement réduite à 40% de la normale.",
	["Coup de tonnerre"] = "Vitesse d'attaque réduite de 30%. Vitesse de déplacement réduite à 27% de la normale.",
	["Gel instantané"] = "Assommée.",
	["Drainer mana"] = "Le lanceur de sort draine 102 points de mana par seconde.",
	["Mot de l'ombre : Douleur"] = "Points de dégâts d'ombre infligés toutes les 3 sec.",
	["Séduction"] = "Séduit.",
	["Toucher débilitant"] = "Force réduite de 40, Endurance réduite de 40,",
	["Eclair de cristal"] = "Assommée.",
	["Inquisition"] = "Les points de dégâts du Sacré subis sont augmentés.",
	["Lucioles"] = "Réduit l’armure de 505, Camouflage ou Invisibilité impossibles.",
	["Geyser"] = "Vitesse de déplacement réduite à 50% de la normale.",
	["Terrifier"] = "Fuit effrayé.",
	["Eclat lunaire"] = "Points de dégâts des Arcanes infligés toutes les 3 sec.",
}

FR_Devour_Order = {
	[1] = "Hex",
	[2] = "Acide corrosif",
	[3] = "Explosion sonore",
	[4] = "Séduction",
	[5] = "Fracas de vagues",
	[6] = "Sommeil cristallin",
	[7] = "Métamorphose",
	[8] = "Silence",
	[9] = "Torpeur",
	[10] = "Hurlement de terreur",
	[11] = "Vulnérabilité à l'ombre",
	[12] = "Transi",
	[13] = "Rugissement glacial",
	[14] = "Eclair de cristal",
	[15] = "Lenteur",
	[16] = "Peur",
	[17] = "Corruption",
	[18] = "Immolation",
	[19] = "=== In/Out Combat Line ===",
	[20] = "Marque du chasseur",
	[21] = "Trait de choc",
	[22] = "Effet de Corruption sanguine",
	[23] = "Effet Piège explosif",
	[24] = "Flammes sacrées",
	[25] = "Mot de l'ombre : Douleur",
	[26] = "Drainer mana",
	[27] = "Marteau de la justice",
	[28] = "Jugement de lumière",
	[29] = "Drainer la vie",
	[30] = "Eclair de givre",
	[31] = "Inquisition",
	[32] = "Cône de froid",
	[33] = "Effet Piège de givre",
	[34] = "Nova de givre",
	[35] = "Effet Piège gelant",
	[36] = "Jugement du Croisé",
	[37] = "Vulnérabilité au feu",
	[38] = "Bannir",
	[39] = "Effet Piège immolation",
	[40] = "Eclat lunaire",
	[41] = "Lucioles",
	[42] = "Sarments",
	[43] = "Jugement de justice",
	[44] = "Geyser",
	[45] = "Trait de glace",
	[46] = "Horion de givre",
	[47] = "Conséquences",
	[48] = "Rafale de flammes",
	[49] = "Intimidation",
	[50] = "Coup de tonnerre",
	[51] = "Champignon de Mirefin",
	[52] = "Jugement d'autorité",
	[53] = "Effrayer une bête",
	[54] = "Griffe de glace",
	[55] = "Horion de flammes",
	[56] = "Coup de bouclier - silencieux",
	[57] = "Bombe fumigène",
	[58] = "Siphon de vie",
	[59] = "Coupure d'ailes améliorée",
	[60] = "Détection de la magie",
	[61] = "Amplifier flammes",
	[62] = "Linceul de vents",
	[63] = "Jugement de sagesse",
	[64] = "Pétrifier",
	[65] = "Fouet malveillant",
	[66] = "Flèche de givre",
	[67] = "Faiblesse",
	[68] = "Mot de l'ombre : Douleur",
	[69] = "Geler sur place",
	[70] = "Vision télépathique",
	[71] = "Drain de vie",
	[72] = "Hurlement terrifiant",
	[73] = "Terrifier",
	[74] = "Frappe fantôme",
	[75] = "Drain de mana",
	[76] = "Bannir le Démon",
	[77] = "Effet Piège givrant",
	[78] = "Aveuglement",
	[79] = "Fragilité",
	[80] = "Gel instantané",
	[81] = "Rendre fou",
	[82] = "Coup fané",
	[83] = "Lien à la terre",
	[84] = "Toucher débilitant",
	[85] = "Gelé",
}

FR_Spell_Lock_List = {
}

FR_Spell_Lock_Order = {
				[1] = "=== Spell Lock ===",
}

FR_Class_Order = {
				[1] = "Druide",
				[2] = "Chasseur",
				[3] = "Mage",
				[4] = "Paladin",
				[5] = "Prêtre",
				[6] = "Voleur",
				[7] = "Chaman",
				[8] = "D\195\169moniste",
				[9] = "Guerrier",
				[10] = "=== Class Priority ===",
}

English_Spell_Lock_List = {
	["Renew"] = "Observed",
	["Holy Light"] = "Observed",
	["Healing Wave"] = "Observed",
	["Immolate"] = "Observed",
	["Polymorph"] = "Observed",
	["Aimed Shot"] = "Observed",
	["Hibernate"] = "Observed",
	["Starfire"] = "Observed",
	["Summon Blackhand Dreadweaver"] = "Observed",
	["Summon"] = "Observed",
	["Gordok Green Grog"] = "Observed",
	["Firebolt"] = "Observed",
	["Concussive Shot"] = "Observed",
	["Chain Lightning"] = "Observed",
	["Fireball"] = "Observed",
	["Regrowth"] = "Observed",
	["Scatter Shot"] = "Observed",
	["Scorpid Sting"] = "Observed",
	["Scarshield Portal"] = "Observed",
	["Howl of Terror"] = "Observed",
	["Summon Succubus"] = "Observed",
	["Strength of Arko'narin"] = "Observed",
	["Wing Buffet"] = "Observed",
	["Ghost Wolf"] = "Observed",
	["Serpent Sting"] = "Observed",
	["Entangling Roots"] = "Observed",
	["Pyroblast"] = "Observed",
	["Fire Shield IV"] = "Observed",
	["The Big One"] = "Observed",
	["Summon Felsteed"] = "Observed",
	["Greater Heal"] = "Observed",
	["Summon Dreadsteed"] = "Observed",
	["Banish"] = "Observed",
	["Fear"] = "Observed",
	["Seduction"] = "Observed",
	["Arcane Shot"] = "Observed",
	["Flash Heal"] = "Observed",
	["Arcane Explosion"] = "Observed",
	["Smite"] = "Observed",
	["Flash of Light"] = "Observed",
	["Shadow Bolt Volley"] = "Observed",
	["Black Sludge"] = "Observed",
	["Enfeeble"] = "Observed",
	["Healing Touch"] = "Observed",
	["Flame Breath"] = "Observed",
	["Mind Control"] = "Observed",
	["Mana Burn"] = "Observed",
	["Fanatic Blade"] = "Observed",
	["Frostbolt"] = "Observed",
	["Curse of the Firebrand"] = "Observed",
	["Conflagrate"] = "Observed",
	["Mind Blast"] = "Observed",
	["Viper Sting"] = "Observed",
	["Bellowing Roar"] = "Observed",
	["Shadowguard"] = "Observed",
	["Scorch"] = "Observed",
	["Flamecrack"] = "Observed",
	["Mark of Flames"] = "Observed",
	["Fireball Volley"] = "Observed",
	["Thorium Grenade"] = "Observed",
	["Shadow Bolt"] = "Observed",
	["Prayer of Healing"] = "Observed",
	["Lightning Bolt"] = "Observed",
	["Dominate Mind"] = "Observed",
	["Breath"] = "Observed",
	["Flame Buffet"] = "Observed",
	["Summon Charger"] = "Observed",
	["Searing Pain"] = "Observed",
	["Heal"] = "Observed",
	["Arcane Bolt"] = "Observed",
	["Summon Warhorse"] = "Observed",
	["Flamestrike"] = "Observed",
	["Defibrillate"] = "Observed",
	["Summon Blackhand Veteran"] = "Observed",
	["Far Sight"] = "Observed",
}

English_Spell_Lock_Order = {
	[1] = "Mana Burn",
	[2] = "Heal",
	[3] = "Healing Wave",
	[4] = "Fireball",
	[5] = "Shadow Bolt Volley",
	[6] = "Immolate",
	[7] = "Shadow Bolt",
	[8] = "=== Spell Lock ===",
	[9] = "Fanatic Blade",
	[10] = "Serpent Sting",
	[11] = "Firebolt",
	[12] = "Strength of Arko'narin",
	[13] = "Holy Light",
	[14] = "Concussive Shot",
	[15] = "Polymorph",
	[16] = "Pyroblast",
	[17] = "Lightning Bolt",
	[18] = "Enfeeble",
	[19] = "Scorpid Sting",
	[20] = "Regrowth",
	[21] = "Renew",
	[22] = "Frostbolt",
	[23] = "Summon Blackhand Dreadweaver",
	[24] = "Summon Blackhand Veteran",
	[25] = "Viper Sting",
	[26] = "Flamestrike",
	[27] = "Fireball Volley",
	[28] = "Flame Breath",
	[29] = "Flame Buffet",
	[30] = "Black Sludge",
	[31] = "Fire Shield IV",
	[32] = "Wing Buffet",
	[33] = "Breath",
	[34] = "Bellowing Roar",
	[35] = "Gordok Green Grog",
	[36] = "Dominate Mind",
	[37] = "Arcane Bolt",
	[38] = "Curse of the Firebrand",
	[39] = "Mark of Flames",
	[40] = "Chain Lightning",
	[41] = "Thorium Grenade",
	[42] = "Flamecrack",
	[43] = "Summon",
	[44] = "Shadowguard",
	[45] = "Mind Control",
	[46] = "Scarshield Portal",
	[47] = "Arcane Shot",
	[48] = "Flash of Light",
	[49] = "Mind Blast",
	[50] = "Flash Heal",
	[51] = "Entangling Roots",
	[52] = "Smite",
	[53] = "Defibrillate",
	[54] = "Scorch",
	[55] = "Starfire",
	[56] = "Healing Touch",
	[57] = "Howl of Terror",
	[58] = "Hibernate",
	[59] = "Seduction",
	[60] = "Scatter Shot",
	[61] = "Fear",
	[62] = "Ghost Wolf",
	[63] = "Arcane Explosion",
	[64] = "Aimed Shot",
	[65] = "Banish",
	[66] = "Summon Succubus",
	[67] = "Summon Dreadsteed",
	[68] = "Far Sight",
	[69] = "Greater Heal",
	[70] = "Searing Pain",
	[71] = "Summon Felsteed",
	[72] = "Conflagrate",
	[73] = "Prayer of Healing",
	[74] = "Summon Charger",
	[75] = "The Big One",
	[76] = "Summon Warhorse",
}

English_Class_Order = {
				[1] = "Druid",
				[2] = "Hunter",
				[3] = "Mage",
				[4] = "Paladin",
				[5] = "Priest",
				[6] = "Rogue",
				[7] = "Shaman",
				[8] = "Warlock",
				[9] = "Warrior",
				[10] = "=== Class Priority ===",
}

English_Magical_Debuff_List = {
	["Corruption"] = "74 Shadow damage every 3 seconds.",
	["Drowning Death"] = "Swim speed reduced by 20%. Agility reduced by 15%.",
	["Sonic Burst"] = "Cannot cast spells.",
	["Blackout"] = "Blacked Out.",
	["Shadow Word: Pain"] = "Shadow damage inflicted every 3 sec.",
	["Immolate"] = "97 Fire damage every 3 seconds.",
	["Judgement of the Crusader"] = "Increases Holy damage taken by up to 140.",
	["Crusader's Hammer"] = "Stunned.",
	["Frost Trap Effect"] = "Movement slowed to 40% of normal.",
	["Frostbite"] = "Frozen.",
	["Freeze"] = "Stunned. Frost damage inflicted every 3 sec.",
	["Counterspell - Silenced"] = "Silenced.",
	["Drain Life"] = "Drains 71 health each second to the caster.",
	["Enslave Demon"] = "Enslaved.",
	["Drain Mana"] = "Drains 140 mana each second to the caster.",
	["Befuddlement"] = "Casting speed reduced by 50%.",
	["Frost Nova"] = "Frozen in place.",
	["Concussive Shot"] = "Movement slowed to 50% of normal.",
	["Shackle Undead"] = "Shackled.",
	["Unholy Curse"] = "Physical damage done reduced by 15.",
	["Aftermath"] = "Movement slowed by 50%.",
	["Spitelash"] = "Physical damage taken is increased by 43 to 57.",
	["Tainted Blood Effect"] = "Attack power reduced by 120.",
	["Shield Bash - Silenced"] = "Silenced.",
	["Flash Freeze"] = "Stunned.",
	["Banshee Shriek"] = "Cannot cast spells.",
	["Fear"] = "Feared.",
	["Hex"] = "Hexed.",
	["Howl of Terror"] = "Fleeing in terror.",
	["Phantom Strike"] = "Decreases armor by 100.  Cannot stealth or turn invisible.",
	["Debilitating Touch"] = "Strength reduced by 20. Stamina reduced by 20.",
	["Chilled"] = "Movement slowed to 70% and attacks slowed by 20%.",
	["Impending Doom"] = "2000 Shadow damage inflicted after 10 sec.",
	["Crusader Strike"] = "Holy damage taken is increased.",
	["Cone of Cold"] = "Movement slowed to 50%.",
	["Terrifying Screech"] = "Fleeing in fear.",
	["Sleep"] = "Asleep.",
	["Mark of Flames"] = "Fire damage dealt is increased by 1000.",
	["Panic"] = "Fleeing in fear.",
	["Silence"] = "Silenced.",
	["Frost Shot"] = "Movement speed reduced to 40% of normal.",
	["Flame Shock"] = "38 Fire damage every 3 seconds.",
	["Earthbind"] = "Movement reduced to 50% of normal.",
	["Entangling Roots"] = "Rooted.  Causes 25 Nature damage every 3 seconds.",
	["Chill Nova"] = "Reduced movement speed.",
	["Shadow Vulnerability"] = "Shadow damage increased by 20%.",
	["Magma Shackles"] = "Movement speed reduced to 40% of normal.",
	["Stormstrike"] = "Increases Nature damage taken by 20%.",
	["Slowing Ooze"] = "Attack speed reduced by 20%. Movement speed reduced to 20% of normal.",
	["Withering Heat"] = "Maximum health reduced by 35%.",
	["Slow"] = "Attack speed reduced by 35%. Movement speed reduced to 40% of normal.",
	["Ancient Despair"] = "Confused.",
	["Fire Vulnerability"] = "Increases Fire damage taken by 4%.",
	["Freezing Trap Effect"] = "Frozen.",
	["Smite Demon"] = "Stunned.",
	["Incite Flames"] = "Fire resistance reduced by 250.",
	["Banish"] = "Invulnerable, but unable to act.",
	["Mind Control"] = "Charmed.  Attack speed reduced by 20%.",
	["Seduction"] = "Seduced.",
	["Shadowed Silence"] = "Cannot cast spells.",
	["Faerie Fire"] = "Decreases armor by 505.  Cannot stealth or turn invisible.",
	["Moonfire"] = "66 Arcane damage every 3 seconds.",
	["Immolation Trap Effect"] = "138 Fire damage every 3 seconds.",
	["Terrify"] = "Fleeing in fear.",
	["Fang of the Crystal Spider"] = "Decreased attack speed and casting speed.",
	["Consuming Shadows"] = "Movement speed slowed to 70% of normal.",
	["Kick - Silenced"] = "Silenced.",
	["Soul Tap"] = "350 health leeched every 2 sec. 350 mana leeched every 2 sec.",
	["Disjunction"] = "Fire, Frost, and Arcane damage taken is increased by 50%.",
	["Cold Eye"] = "Slowed attack speed.",
	["Siphon Life"] = "Drains 45 health to the caster every 3 secs.",
	["Hammer of Justice"] = "Stunned.",
	["Frostbolt"] = "Movement slowed to 60%.",
	["Frost Shock"] = "Movement slowed to 50% of normal speed.",
	["Judgement of Wisdom"] = "Attacks and spells used against you have a chance of restoring 59 of the attacker's mana.",
	["Mind Vision"] = "Sight granted through target's eyes.",
	["Ancient Dread"] = "Casting speed reduced by 50%. Attack speed reduced by 50%.",
	["Explosive Trap Effect"] = "33 Fire damage every 2 seconds.",
	["Soul Burn"] = "4000 Fire damage inflicted over 16 sec. Physical damage dealt is decreased by 50%. Silenced.",
	["Hunter's Mark"] = "All attackers gain 110 Ranged Attack Power against this target.",
	["Polymorph"] = "Cannot attack or cast spells.  Increased regeneration.",
	["Holy Fire"] = "33 Fire damage every 2 seconds.",
	["Judgement of Light"] = "Melee attacks made against you have a chance of causing the attacker to be healed for 61.",
	["Hibernate"] = "Asleep.",
	["Ink Spray"] = "Chance to hit reduced by 50%.",
	["Frailty"] = "All attributes reduced by 10.",
	["Cauterizing Flames"] = "Fire resistance reduced by 200.",
	["Dominate Mind"] = "Charmed.",
	["Screams of the Past"] = "Cannot cast spells.",
	["Flame Buffet"] = "Increased Fire damage taken.",
	["Improved Wing Clip"] = "Immobilized.",
	["Ignite Mana"] = "400 mana and health burned every 3 sec.",
	["Thunderclap"] = "Attack speed reduced by 25%. Movement speed reduced to 45% of normal.",
	["Detect Magic"] = "Magic detection.",
	["Entrapment"] = "Immobile.",
	["Frostbolt Volley"] = "Movement speed reduced to 50% of normal.",
	["Cripple"] = "Movement speed reduced to 50% of normal. Attack speed reduced by 50%. Strength reduced by 50%.",
	["Wither Strike"] = "Attack speed reduced by 33%.",
	["Crystallize"] = "Stunned.",
}
		
English_Devour_Order = {
	[1] = "Incite Flames",
	[2] = "Entrapment",
	[3] = "Befuddlement",
	[4] = "Fang of the Crystal Spider",
	[5] = "Sonic Burst",
	[6] = "Disjunction",
	[7] = "Panic",
	[8] = "Crystallize",
	[9] = "Kick - Silenced",
	[10] = "Screams of the Past",
	[11] = "Chill Nova",
	[12] = "Consuming Shadows",
	[13] = "Slow",
	[14] = "Soul Tap",
	[15] = "Slowing Ooze",
	[16] = "Banshee Shriek",
	[17] = "Thunderclap",
	[18] = "Freeze",
	[19] = "Hibernate",
	[20] = "Mind Control",
	[21] = "Shadowed Silence",
	[22] = "Flash Freeze",
	[23] = "Blackout",
	[24] = "Frostbite",
	[25] = "Howl of Terror",
	[26] = "Seduction",
	[27] = "Sleep",
	[28] = "Crusader's Hammer",
	[29] = "Shield Bash - Silenced",
	[30] = "Hammer of Justice",
	[31] = "Concussive Shot",
	[32] = "Aftermath",
	[33] = "Cone of Cold",
	[34] = "Frostbolt",
	[35] = "Chilled",
	[36] = "Frost Nova",
	[37] = "Frost Shot",
	[38] = "Frostbolt Volley",
	[39] = "Hex",
	[40] = "Ignite Mana",
	[41] = "Cripple",
	[42] = "Impending Doom",
	[43] = "Dominate Mind",
	[44] = "Mark of Flames",
	[45] = "Withering Heat",
	[46] = "Ancient Despair",
	[47] = "Ancient Dread",
	[48] = "Cauterizing Flames",
	[49] = "Soul Burn",
	[50] = "Silence",
	[51] = "Counterspell - Silenced",
	[52] = "Polymorph",
	[53] = "Fear",
	[54] = "Terrify",
	[55] = "Terrifying Screech",
	[56] = "Shadow Word: Pain",
	[57] = "Corruption",
	[58] = "Immolate",
	[59] = "Entangling Roots",
	[60] = "Frost Shock",
	[61] = "Moonfire",
	[62] = "=== In/Out Combat Line ===",
	[63] = "Drain Life",
	[64] = "Shadow Vulnerability",
	[65] = "Debilitating Touch",
	[66] = "Earthbind",
	[67] = "Faerie Fire",
	[68] = "Flame Shock",
	[69] = "Hunter's Mark",
	[70] = "Holy Fire",
	[71] = "Crusader Strike",
	[72] = "Drain Mana",
	[73] = "Siphon Life",
	[74] = "Tainted Blood Effect",
	[75] = "Phantom Strike",
	[76] = "Enslave Demon",
	[77] = "Banish",
	[78] = "Judgement of the Crusader",
	[79] = "Detect Magic",
	[80] = "Stormstrike",
	[81] = "Shackle Undead",
	[82] = "Mind Vision",
	[83] = "Frost Trap Effect",
	[84] = "Explosive Trap Effect",
	[85] = "Flame Buffet",
	[86] = "Cold Eye",
	[87] = "Frailty",
	[88] = "Judgement of Light",
	[89] = "Wither Strike",
	[90] = "Freezing Trap Effect",
	[91] = "Unholy Curse",
	[92] = "Immolation Trap Effect",
	[93] = "Drowning Death",
	[94] = "Fire Vulnerability",
	[95] = "Magma Shackles",
	[96] = "Ink Spray",
	[97] = "Spitelash",
	[98] = "Smite Demon",
	[99] = "Judgement of Wisdom",
	[100] = "Improved Wing Clip",
}

-- Ok, here comes the important stuff so that the addon runs on the Euro client

if (GetLocale() == "frFR") then
	ServitudeLocalization = 
	{
		Class = "D\195\169moniste";
		Class2 = "Guerrier";
		Class3 = "Chaman";
		Class4 = "Paladin";
		Pet1 = "Diablotin";
		Pet2 = "Voidwalker";
		Pet3 = "Succube";
		Pet4 = "Felhunter";
		Pet5 = "Doomguard";
		Magic1 = "Invisibilit\195\169 mineure";
		Magic2 = "Baiser apaisant";
		Magic3 = "Consumer les ombres";
		Magic4 = "Sacrifice";
		Magic5 = "Festin magique";
		Magic6 = "Tourment";
		Magic7 = "Bouclier de feu";
		Magic8 = "S\195\169duction";
		Magic9 = "Verrou magique";
		Magic10 = "Dissiper Magie";
		Magic11 = "Fouet de Douleur";
		Magic12 = "Bannir";
		Magic13 = "Eclair de feu";
		Magic14 = "Souffrance";
		Magic15 = "Malédiction des Ténèbres";
		Magic16 = "Malédiction des Eléments";
		Buff1 = "SacrificialShield";
		Buff2 = "Nature_Swiftness";
		Buff3 = "LesserInvisi";
		Buff4 = "Vision t\195\169l\195\169pathique";
		Buff5 = "Sommeil sans r\195\170ves";
		Buff6 = "Bouclier de feu";
		Buff7 = "Epines";
		Buff8 = "Lien spirituel";
		Buff9 = "Pacte de sang";
		Buff10 = "Aura de R\195\169tribution";
		Buff11 = "Parano\195\175a";
		Bufftype = "Magie";
		NoDesc = "No Text Found";
		CastString = "(.+) commence \195\160 lancer (.+).";
		SedString = "(.+) commence \195\160 lancer S\195\169duction";
		FadeString = "S\195\169duction sur (.+) vient de se dissiper";
		DarkPactString = "Vous drainez %d+ Mana à";
	}	
elseif (GetLocale() == "deDE") then	
	ServitudeLocalization = 
	{
		Class = "Hexenmeister";
		Class2 = "Krieger";
		Class3 = "Schamane";
		Class4 = "Paladin";
		Pet1 = "Wichtel";
		Pet2 = "Leerwandler";
		Pet3 = "Sukkubus";
		Pet4 = "Teufelsjäger";
		Pet5 = "Doomguard";
		Magic1 = "Geringe Unsichtbarkeit";
		Magic2 = "Besänftigender Kuss";
		Magic3 = "Schatten verzehren";
		Magic4 = "Opferung";
		Magic5 = "Magie verschlingen";
		Magic6 = "Qual";
		Magic7 = "Feuerschild";
		Magic8 = "Verführung";
		Magic9 = "Festzaubern";
		Magic10 = "Magiebannung";
		Magic11 = "Schmerzenspeitsche";
		Magic12 = "Verbannen";
		Magic13 = "Feuerblitz";
		Magic14 = "Leiden";
		Magic15 = "Schattenfluch";
		Magic16 = "Fluch der Elemente";
		Buff1 = "SacrificialShield";
		Buff2 = "Nature_Swiftness";
		Buff3 = "Spell_Magic_LesserInvisibilty";
		Buff4 = "Gedankensicht";
		Buff5 = "Traumloser Schlaf";
		Buff6 = "Feuerschild";
		Buff7 = "Dornen";
		Buff8 = "Seelenverbindung";
		Buff9 = "Blutpakt";
		Buff10 = "Aura der Vegeltung";
		Buff11 = "Paranoia";
		Bufftype = "Magie"; 
		NoDesc = "No Text Found";
		CastString = "(.+) beginnt (.+) zu wirken";
		SedString = "(.+) beginnt Verführung zu wirken";
		FadeString = "Verführung schwindet von (.+)%.";
		DarkPactString = "You drain %d+ mana from";
	}
else 
	ServitudeLocalization = 
	{
		Class = "Warlock";
		Class2 = "Warrior";
		Class3 = "Shaman";
		Class4 = "Paladin";
		Pet1 = "Imp";
		Pet2 = "Voidwalker";
		Pet3 = "Succubus";
		Pet4 = "Felhunter";
		Pet5 = "Doomguard";
		Magic1 = "Lesser Invisibility";
		Magic2 = "Soothing Kiss";
		Magic3 = "Consume Shadows";
		Magic4 = "Sacrifice";
		Magic5 = "Devour Magic";
		Magic6 = "Torment";
		Magic7 = "Fire Shield";
		Magic8 = "Seduction";
		Magic9 = "Spell Lock";
		Magic10 = "Dispel Magic";
		Magic11 = "Lash of Pain";
		Magic12 = "Banish";
		Magic13 = "Firebolt";
		Magic14 = "Suffering";
		Magic15 = "Curse of Shadow";
		Magic16 = "Curse of the Elements";
		Buff1 = "SacrificialShield";
		Buff2 = "Nature_Swiftness";
		Buff3 = "Spell_Magic_LesserInvisibilty";
		Buff4 = "Mind Vision";
		Buff5 = "Dreamless Sleep";
		Buff6 = "Fire Shield";
		Buff7 = "Thorns";
		Buff8 = "Soul Link";
		Buff9 = "Blood Pact";
		Buff10 = "Retribution Aura";
		Buff11 = "Paranoia";
		Bufftype = "Magic";
		NoDesc = "No Text Found";
		CastString = "(.+) begins to cast (.+).";
		SedString = "(.+) begins to cast Seduction";
		FadeString = "Seduction fades from (.+)%.";
		DarkPactString = "You drain %d+ Mana from";
	}
end
