

DOCTORBAG_PURIFY				= "Purify";
DOCTORBAG_CLEANSE				= "Cleanse";

DOCTORBAG_DEBUFF_REMOVING		= {
	[DOCTORBAG_PURIFY] = {
		["Poison"] = true;
		["Disease"] = true;
	};
	[DOCTORBAG_CLEANSE] = {
		["Poison"] = true;
		["Disease"] = true;
		["Magic"] = true;
	};
};

DOCTORBAG_BLESSING_OF_KINGS		= "Blessing of Kings";
DOCTORBAG_BLESSING_OF_MIGHT		= "Blessing of Might";
DOCTORBAG_BLESSING_OF_SALVATION	= "Blessing of Salvation";
DOCTORBAG_BLESSING_OF_WISDOM	= "Blessing of Wisdom";
DOCTORBAG_BLESSING_OF_LIGHT		= "Blessing of Light";

DOCTORBAG_PVP_ZONES				= {	
	["Alterac Valley"] = true;
	["Warsong Gulch"] = true;
	["Arathi Basin"] = true;
};

DOCTORBAG_BUFF_TEXTURES 		= {
	[DOCTORBAG_BLESSING_OF_KINGS] = {
		DOCTORBAG_TEXTURE_BLESSING_OF_KINGS,
		DOCTORBAG_TEXTURE_BLESSING_OF_KINGS_GREATER
	};
	[DOCTORBAG_BLESSING_OF_SALVATION] = {
		DOCTORBAG_TEXTURE_BLESSING_OF_SALVATION,
		DOCTORBAG_TEXTURE_BLESSING_OF_SALVATION_GREATER
	};
	[DOCTORBAG_BLESSING_OF_MIGHT] = {
		DOCTORBAG_TEXTURE_BLESSING_OF_MIGHT,
		DOCTORBAG_TEXTURE_BLESSING_OF_MIGHT_GREATER
	};
	[DOCTORBAG_BLESSING_OF_WISDOM] = {
		DOCTORBAG_TEXTURE_BLESSING_OF_WISDOM,
		DOCTORBAG_TEXTURE_BLESSING_OF_WISDOM_GREATER
	};
	[DOCTORBAG_BLESSING_OF_LIGHT] = {
		DOCTORBAG_TEXTURE_BLESSING_OF_LIGHT,
		DOCTORBAG_TEXTURE_BLESSING_OF_LIGHT_GREATER
	};
};

function DoctorBag_MakeGreaterBlessing(blessing)
	return "Greater "..blessing;
end

