MACROFRAME_CHAR_LIMIT = "%d/"..MACRO_MAX_LETTERS.." Characters Used";

--SLASH

SLASH_SUPERMACRO1 = "/supermacro";
SUPERMACRO_HELP_LINE1 = "/supermacro hideaction 1 or 0 to hide or show macro names on action buttons"
SUPERMACRO_HELP_LINE2 = "just /supermacro to show help"
SUPERMACRO_HELP_LINE3 = "/macro <macro_name> to run a macro by name"

--BINDINGS

BINDING_HEADER_SUPERMACROHEADER = "SuperMacro";
BINDING_NAME_TOGGLEMACRO = "Toggle Macro Pane";
BINDING_NAME_SM_ATTACK = "Attack";
BINDING_NAME_SM_PETATTACK = "PetAttack";
BINDING_NAME_SM_MACRO1 = "Macro 1";
BINDING_NAME_SM_MACRO2 = "Macro 2";
BINDING_NAME_SM_MACRO3 = "Macro 3";
BINDING_NAME_SM_MACRO4 = "Macro 4";
BINDING_NAME_SM_MACRO5 = "Macro 5";
BINDING_NAME_SM_MACRO6 = "Macro 6";
BINDING_NAME_SM_MACRO7 = "Macro 7";
BINDING_NAME_SM_MACRO8 = "Macro 8";
BINDING_NAME_SM_MACRO9 = "Macro 9";
BINDING_NAME_SM_MACRO10 = "Macro 10";
BINDING_NAME_SM_MACRO11 = "Macro 11";
BINDING_NAME_SM_MACRO12 = "Macro 12";
BINDING_NAME_SM_MACRO13 = "Macro 13";
BINDING_NAME_SM_MACRO14 = "Macro 14";
BINDING_NAME_SM_MACRO15 = "Macro 15";
BINDING_NAME_SM_MACRO16 = "Macro 16";
BINDING_NAME_SM_MACRO17 = "Macro 17";
BINDING_NAME_SM_MACRO18 = "Macro 18";
BINDING_NAME_SM_MACRO19 = "Macro 19";
BINDING_NAME_SM_MACRO20 = "Macro 20";
BINDING_NAME_SM_MACRO21 = "Macro 21";
BINDING_NAME_SM_MACRO22 = "Macro 22";
BINDING_NAME_SM_MACRO23 = "Macro 23";
BINDING_NAME_SM_MACRO24 = "Macro 24";
BINDING_NAME_SM_MACRO25 = "Macro 25";
BINDING_NAME_SM_MACRO26 = "Macro 26";
BINDING_NAME_SM_MACRO27 = "Macro 27";
BINDING_NAME_SM_MACRO28 = "Macro 28";
BINDING_NAME_SM_MACRO29 = "Macro 29";
BINDING_NAME_SM_MACRO30 = "Macro 30";
BINDING_NAME_SM_MACRO31 = "Macro 31";
BINDING_NAME_SM_MACRO32 = "Macro 32";
BINDING_NAME_SM_MACRO33 = "Macro 33";
BINDING_NAME_SM_MACRO34 = "Macro 34";
BINDING_NAME_SM_MACRO35 = "Macro 35";
BINDING_NAME_SM_MACRO36 = "Macro 36";
