-- Version : French ( by Sasmira )
-- Last Update : 03/21/2005

if ( GetLocale() == "frFR" ) then

EARTH_FEATURES_TITLE="Menu des Caract\195\169ristiques de Earth";

EARTHTREE_KEYWORD_TABLE="{Table}";
EARTHTREE_KEYWORD_BOOL_TRUE="|Vrai|";
EARTHTREE_KEYWORD_BOOL_FALSE="|Faux|";
EARTHTREE_KEYWORD_FUNCTION="*Fonction*";
EARTHTREE_KEYWORD_NIL="nulle";
EARTHTREE_KEYWORD_UNKNOWN="/Type Inconnu/";

EARTHTREE_EXPAND_COLLAPSE="D\195\169velopper/R\195\169duire";
EARTHTREE_EXPAND_INFO="Liens: ";

EARTHTABLE_KEYWORD_TABLE="{Table}";
EARTHTABLE_KEYWORD_FUNCTION="*Fonction*";
EARTHTABLE_KEYWORD_NIL="nule";
EARTHTABLE_KEYWORD_UNKNOWN="/Inconnu/";
EARTHTABLE_KEYWORD_BOOL_TRUE="Vrai";
EARTHTABLE_KEYWORD_BOOL_FALSE="Faux";

end